### PR TITLE
Updates of NectarCam and LSTCam real data eventsource class

### PR DESCRIPTION
**Pull request by FrancaCassol**
Added the instrument information to the real data containers. The camera geometry files have been adde to the ctapipe-extra repository. They are:
- LSTCam-001.camgeom.fits.gz = present geometry of the LST1 camera (001 indicate the version)
- NectarCam-001.camgeom.fits.gz = present geometry of the NectarCam prototype (001 indicate the version)

The optics is the one of MC data.

### CODE REVIEW

**Comment by kosack** [comment]
I just created and uploaded a new version of `ctapipe-extra`,  which should allow the tests to work in this PR.

**Comment by FrancaCassol** [comment]
I am not really sure on where is the problem here, is it perhaps simply due to the version number in the camera geometry name?

**Comment by kosack** [comment]
it seems the tests are failing due to a bug in getting the list of known camera names: perhaps related to a file naming convention .  I'll check

**Comment by FrancaCassol** [comment]
Hi, 
This PL is blocked because it does to find the resources in ctapipe-extra (at least at the moment)
Would be possible to fix it? Next week there will be the LST analysis bootcamp and it would be nice to have this PL accepted.

Thanks!
Cheers
Franca

**Comment by FrancaCassol** [comment]
PS: I mean PL not PR ;-)

**Comment by MaxNoe** [comment]
This is because the files in `ctapipe-extra` have a bug as Carl mentioned before. the `VERSION` header key word does not match the filename. You should update these first I guess.

**Comment by FrancaCassol** [comment]
Ok, I missed totally this comment of Karl (actually now the geometry is 2), where did he wrote it?

What should I use: 002 or 2? (for both indeed)

**Comment by MaxNoe** [comment]
I have no strong optionin on that. For sorting the files leading zeros might be nice if you expect more than 9 versions.

**Comment by FrancaCassol** [comment]
Sorry, I am still not sure to understand where is the problem. Could you please indicate me the place where karl peak about that?
Thanks

**Comment by MaxNoe** [comment]
The issue is #813

**Comment by MaxNoe** [comment]
If I understood @kosack correctly, it is assumend that the filename and the `CAM_ID` are identical, so:

```
In [1]: from astropy.io import fits                                                                                                            
In [2]: f = fits.open('LSTCam-001.camgeom.fits.gz')                                                                                            
In [3]: 'LSTCam-001.camgeom.fits.gz'.split('.')[0]                                                                                             
Out[3]: 'LSTCam-001'
```
Is not supported at the moment.
In [4]: f[1].header['CAM_ID']                                                                                                                  
Out[4]: 'LST1Cam

**Comment by MaxNoe** [comment]
See also this issue:
https://github.com/cta-observatory/ctapipe-extra/issues/13

**Comment by FrancaCassol** [comment]
But I made a PR in ctapipe-extra, so solve this problem solved: [https://github.com/cta-observatory/ctapipe-extra/pull/14#issue-231899562](url)

However it seems to me that this PR is blocked because it doesn't find the NectarCAM data in ctapipe-extra: 
E   FileNotFoundError: Couldn't find resource: 'NectarCAM.Run0890.10events.fits.fz'

?

**Comment by MaxNoe** [comment]
I think you need to wait until this is merged, a new version is tagged and then update the ctapipe-extra version in `.travis.yml`

**Comment by FrancaCassol** [comment]
Dear all,
is there any chance to get (in a close future ;-) ) a new release of ctapipe-extra (v0.2.16) with the correct LST and NectarCAM camera geometries? This is blocking this pull request since several weeks. 

Otherwise, if this is not the correct way to proceed, could you please suggest me how to go further?
Thanks for any hint

Cheers
Franca

**Comment by FrancaCassol** [comment]
Dear all,
I didn't get any reply to my last comment. 
LST1 starts to take data and this missing accepted PR is very annoying for a lot of people. 

I retry:
As far I understand this PR is blocked by a missing new release of ctapipe-extra. Can somebody help to de-block the situation? (any proposed solution will be welcome)

Thanks very much

Cheers
Franca

**Comment by FrancaCassol** [comment]
Hi, I wonder if this PR can be accepted like that or I need to make a new push in my fork (where I changed the three remained style errors). I see from the merging the ctapipe HEAD that a lot of things changed and I wonder if this action will make a mess...

**Comment by FrancaCassol** [comment]
In the case the PR can be accepted like that, please can you do it?

**Pull request merged**
