### PR TITLE
Match data types of default values and calculated parameters

### PR DESCRIPTION
**Pull request by LukasNickel**
Quick and easy fix for #1597 and connected issues.
It is still not apparent to me why we use single precision at one place and double precision at another though.

### CODE REVIEW

**Comment by maxnoe** [comment]
Will depend on the input types sometimes. Quantities will cast everything to float64 I think by default. If it isn't a quantity, it probaly inherits the type when using plain numpy transformations.

**Comment by maxnoe** [comment]
I would rather be consistent here.

 I don't think we have any image parameters where we need 64 bits. So let's make sure all are 32? @kosack?

For example in `leakage_parameters`, that would mean doing `

```
return LeakageContainer(
    pixels_width_1=(leakage_pixel1 / geom.n_pixels).astype(np.float32),
   ...
)
```

However, as stated before, I would probably rather implement this by allowing `Field.validate` to cast to the dtype.

**Comment by maxnoe** [comment]
Which can be done using `astype(casting='same_type')` which only allows casts between different sizes of the same type, so e.g. `float32 ↔ float64` but not `int64 ↔ float64`

**Comment by maxnoe** [comment]
I was wrong about quantity, it preserves float dtype:

```
In [10]: image = np.random.normal(size=1855).astype('float32')
In [11]: u.Quantity(image.sum(), u.m).dtype
Out[11]: dtype('float32')
```

**Comment by LukasNickel** [comment]
Do we need the double precision during the calculation?
If not we can just remove the upcasting in the hillas parameters and only worry about numba code

**Comment by LukasNickel** [comment]
Although field.validate seeme like the nicest way to handle this.

**Comment by maxnoe** [comment]
Yes, I think internally using `flaot64` for all image parameters and then when writing casting to `float32` makes most sense

**Comment by LukasNickel** [comment]
Should we upcast in the parameter function itself, like here:
 https://github.com/cta-observatory/ctapipe/blob/23bf35655f9d6bd0215dba024cadc09187c2ac40/ctapipe/image/hillas.py#L111-L113

or would it be easier to upcast the image once in the `ImageProcessor` and remove that code?

**Comment by maxnoe** [comment]
Let's merge this as is for a hotfix so it can go into 0.10.2 and do the conversion stuff for 0.11.

THis way, we might get it to work today for johan to start processing the data on the grid.

**Review by maxnoe — APPROVED** [review]

**Review by kosack — APPROVED** [review]
it's strange this didn't happen earlier (I never saw it in any of my tests or large productions), but it clearly is wrong.  Maybe an older version of some dependency was more lenient.

**Pull request merged**
