### PR TITLE
Return nan for non-invertible matrices

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by MaxNoe** [comment]
@HealthyPear could you try the file that failed with this PR?

**Review by kosack — APPROVED** [review]

**Comment by MaxNoe** [comment]
@HealthyPear tested this on a large simtel file that crashed before which now worked fine.

**Review by HealthyPear — APPROVED** [review]

**Comment by kosack** [comment]
I think this is ok now, but we should check that in all places it is used, we ensure that NaN is an ok result. I guess the only critical place will be in the second pass of the TwoPassWindowSum, otherwise this info is not used, only written to the disk.

**Comment by MaxNoe** [comment]
Ok, let's merge this and then check how algorithms using this one handle the nan cases.

**Pull request merged**
