### PR TITLE
Make devs aware of debugging and `ipdb` in docs

### PR DESCRIPTION
**Pull request by StFroese**

### CODE REVIEW

**Comment by StFroese** [comment]
discussed in #2149

**Comment by kosack** [comment]
It would be good to also show how to run a command-line tool in a debugger with and without having to add a `breakpoint()` line.    I think if you add a `breakpoint()` with an appropriate PYTHONDEBUG set, running e.g. `ctapipe-process` should work fine.    But sometimes you don't want to edit the code, and instead can run the tool directly in debug mode like this:

```sh
python -m pdb -m ctapipe.tools.process [usual command-line options]
```

**Comment by nbiederbeck** [comment]
I would also add `pytest --pdb` in this section

**Comment by Tobychev** [comment]
I recently found [pudb]( https://documen.tician.de/pudb/index.html) which is a pretty nice if somewhat quirky terminal debugger.

**Comment by kosack** [comment]
It seem the jobs here are failing, and there is no "restart" button - perhaps push a blank commit and we can just review/merge this?

**Comment by maxnoe** [comment]
This needs a rebase with main, to e.g. include the fixes for the memory problem (which is I think the issue for the CI failure here).

The reason for the absence of a restart button is probably that github doesn't allow restarting jobs indefinitely.

**Comment by maxnoe** [comment]
Rebased vs. main now

**Review by kosack — APPROVED** [review]

**Review by Tobychev — APPROVED** [review]

**Pull request merged**
