### PR TITLE
Do not share `connexions` member variable among instances

### PR DESCRIPTION
**Pull request by tristan0x**
Default arguments should be not mutable.

### CODE REVIEW

**Comment by tristan0x** [comment]
After looking at the Travis build log, I am not sure my patch is responsible for the failure, is it?

**Comment by MaxNoe** [comment]
@tristan0x No it isn't

Also, why is this called `connexions`? Shouldn't it be `connections`?

**Comment by tristan0x** [comment]
Hi @MaxNoe 

I agree with you. I just reused the previous member variable name.
Should I renamed it to `connections` ?

**Comment by MaxNoe** [comment]
@tristan0x I would say so.

**Comment by kosack** [comment]
there are actually a lot of language problems in this module (french vs english words). The software standards docs specify to use english spelling (or american depending on preference).  

So at least:
* connexion → connection
* processus → process

Using the refactor→rename functionality in PyCharm makes this quite easy to do

**Comment by tristan0x** [comment]
I fixed the language problems in a separate PR: #425

**Pull request merged**
