### PR TITLE
Colored log output

### PR DESCRIPTION
**Pull request by watsonjj**
Created new logging.Formatter for Tool logger so that levels have colored format

### CODE REVIEW

**Comment by MaxNoe** [comment]
There is: https://pypi.python.org/pypi/colorlog, maybe it's interesting for the task.

**Comment by kosack** [comment]
isn't that already the case if we use the astropy logging?  It comes out in color for me.

**Comment by kosack** [comment]
though I'm happy to have a local version, since it would be nice to abandon the dependency on astropy-helpers

**Comment by watsonjj** [comment]
Yes that is true if you use the astropy logger. However the Tool logger is instead from the traitlets Application module. These are two individual loggers configured differently.

**Comment by kosack** [comment]
also, we need this to be able to be disabled if the terminal doesn't support color, or if the log is redirected to a file, so you don't get non-printable characters.  I think that is possible since I've seen other code that does it (and I've done similar in C++).   Alternately what we can do is always write the log to the screen and a file (using the logger's ability to have two streams), and have only the screen one formatted in color.

**Comment by kosack** [comment]
aha. one way to do it is to use the  "colorama" package (in anaconda) instead of doing the ANSI escape-sequences manually. It adds yet another dependency, but it's small, and it automatically turns off if the output is redirected to a file. 

https://github.com/tartley/colorama

**Comment by watsonjj** [comment]
Okay, I will look into changing this pull request to use colorama in the Tool logger later

**Pull request merged**
