### PR TITLE
coordinates example notebook

### PR DESCRIPTION
**Pull request by thomasgas**
I prepared this notebook on the coordinates for the 1st LST Bootcamp in Padova (26-30/11/2018).
After some changes (thanks @MaxNoe for the help) I re-uploaded it in the cta-lstchain repository.
Since the coordinates are a matter also of ctapipe, I'm uploading this notebook also here.
This is related to #842 and PR referenced in my comment inside (#727 and #753).
Feel free to comment on this.

### CODE REVIEW

**Comment by mackaiver** [comment]
Change 
`cal = CameraCalibrator(None, None, r1_product='HESSIOR1Calibrator', extractor_product='NeighbourPeakIntegrator')`

to `cal = CameraCalibrator(event_source)`

**Comment by MaxNoe** [comment]
You should use a context manager with the eventsource probably, but yes. See my notebook for the LST meeting

**Comment by thomasgas** [comment]
This notebook will be changes accordingly to #896.

**Comment by kosack** [comment]
The tests are failing since notebooks must be able to execute, and CREED_VTK is not installed.

I'd suggest either:
1) mark this notebook as xfail ("expected to fail") in `execute_ipynbs.py`, which will prevent the tests from running at all on that notebook
2) build a conda package for your CREED_VTK and upload it to anaconda cloud, and we can include it in the environment.yaml (at the risk of slowing down the install process and adding more non-required packages to the testing env)

**Comment by thomasgas** [comment]
> The tests are failing since notebooks must be able to execute, and CREED_VTK is not installed.
> 
> I'd suggest either:
> 
>     1. mark this notebook as xfail ("expected to fail") in `execute_ipynbs.py`, which will prevent the tests from running at all on that notebook
> 
>     2. build a conda package for your CREED_VTK and upload it to anaconda cloud, and we can include it in the environment.yaml (at the risk of slowing down the install process and adding more non-required packages to the testing env)

I think that option 1 is fine for me since the VTK library that my CREED_VTK depends on is 50 Mb and not really mandatory. If someone wants to play with this, they can install the library.

**Comment by MaxNoe** [comment]
I would suggest to remove that CREED_VTK part. This notebook is to usefull of an example to not be tested.

**Comment by thomasgas** [comment]
> I would suggest to remove that CREED_VTK part. This notebook is to usefull of an example to not be tested.

Fine for me. 
I think the notebook will need to be refactored a bit after the coordinate PR has been merged, right @MaxNoe?

**Comment by MaxNoe** [comment]
Yes, I would wait for that.

**Comment by thomasgas** [comment]
I'm re-working on the coordinates notebook after the major PR on coordinates. I'll also put in the notebook also some examples that was put by @MaxNoe during the discussion in the coordinates PR. 
Maybe you wrote this somewhere but i missed it: In which folder should I put the notebook after #941 has moved things around?

**Comment by dneise** [comment]
Notebooks are now in `ctapipe/docs/examples/`

**Comment by kosack** [comment]
this notebook still does not run in sphinx.  Could you fix it?
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-bf428597381b> in <module>
----> 1 from ctapipe.coordinates import HorizonFrame, GroundFrame, TiltedGroundFrame
      2 from ctapipe.coordinates import NominalFrame, CameraFrame, TelescopeFrame
ImportError: cannot import name 'HorizonFrame' from 'ctapipe.coordinates' (/home/travis/build/cta-observatory/ctapipe/ctapipe/coordinates/__init__.py)
ImportError: cannot import name 'HorizonFrame' from 'ctapipe.coordinates' (/home/travis/build/cta-observatory/ctapipe/ctapipe/coordinates/__init__.py)
```

**Comment by MaxNoe** [comment]
See #1075

**Pull request closed without merging**
