### PR TITLE
Import all ctapipe_ plugins, not just IO. Add test with dummy plugin

### PR DESCRIPTION
**Pull request by maxnoe**
* Import all plugin packages (moved to __init__.py, removed restriction on `ctapipe_io` to `ctapipe_` prefix
* Test a dummy plugin for unit tests

TODO:

- [ ] Add hooks in ctapipe process to call reconstructor plugins?
- [ ] Add hooks in `DataWriter` so that plugins can store additional information in output files?

### CODE REVIEW

**Comment by kosack** [comment]
Sounds reasonable.  This allows also one to replace any class that has a "type" option in the configuration with a custom one. E.g. a new ImageCleaner that isn't already included. 

If all classes can be selected by name at configure-time, perhaps hooks aren't needed explicitly between steps in the event loops. 

E.g. to add a step to shower processor, one only needs to do:
```py3
class MyShowerProcessor(ShowerProcessor):
    def __call__(self, event)
         super().__call__(self, event)
         # do some more stuff
```

Then in the config file, if the plugin is loaded, they can just specify `shower_processor_type=MyShowerProcessor`

```

**Comment by maxnoe** [comment]
> If all classes can be selected by name at configure-time, perhaps hooks aren't needed explicitly between steps in the event loop.

I was thinking about the possibility of adding additional steps (like LST doing the muon calibration) or prototyping deep learning end-to-end or multi output steps. 

Somthing like:
```
post_dl1_components:
     - LSTMuonExtraction
```

and in `process`:

```
self._post_dl1_components = [
     Component.from_name(name, parent=self)
    for name in self.post_dl1_components
]
```


```
for component in self._post_dl1_compoents:
     component(event)
```

**Comment by kosack** [comment]
Ah, ok yes that makes sense. So having a hook for a component before DL1 and after DL1 would be useful.

**Comment by kosack** [comment]
> self._post_dl1_components = [
 >    Component.from_name(name, parent=self)
>    for name in self.post_dl1_components
> ]

Might have to deal with the case where the component is a TelescopeComponent, and therefore needs a SubarrayDescription as well.

**Comment by maxnoe** [comment]
Superseeded by #2101

**Pull request closed without merging**
