### PR TITLE
Add Monitoring container to MC data

### PR DESCRIPTION
**Pull request by FrancaCassol**
Waiting for a better solution concerning the handing of Monitoring data in ctapipe, I propose to change the DataContainer() in simteleventsource.py with an EventAndMonDataContainer() .
This should permit to test the calibration tools with MC data following the same procedure used for real data.

### CODE REVIEW

**Comment by kosack** [comment]
Is the idea then to later fill the mon containers from simulations?

**Comment by FrancaCassol** [comment]
Exactly.

**Comment by FrancaCassol** [comment]
Hi @kosack,

could you please merge this PR?
Thanks

**Comment by MaxNoe** [comment]
This only exchanges the class of this container in the SimtelEventSource.
It does not fill it. 

What is the reason, the the `mon` field is not just added to `DataContainer`?

**Comment by FrancaCassol** [comment]
Hi @MaxNoe,

> This only exchanges the class of this container in the SimtelEventSource.
> It does not fill it.

the container  will be filled by the calibration scripts (as for the data).

> What is the reason, the the `mon` field is not just added to `DataContainer`?

I made this choice to separate the event and the monitoring level. As said, this
is surely not the final/better solution, but it works fine at least at R1 level.

**Pull request merged**
