### PR TITLE
Update bokeh plotters to handle nan

### PR DESCRIPTION
**Pull request by watsonjj**
The bokeh plotter will now correctly plot nan as a transparent pixel

### CODE REVIEW

**Comment by MaxNoe** [comment]
> Checked changes on local master branch, behaves as expected. Should we make sure that mpl_camera behaves the same way when supplied with nan values?

This is not the default and would require creating custom colormaps and converting everything into masked arrays. I don't know, if that is a good idea.

**Comment by kosack** [comment]
>Checked changes on local master branch, behaves as expected. Should we make sure that mpl_camera behaves the same way when supplied with nan values?

I think it already does, but couldn't hurt to add a unit test at least to ensure it doesn't crash

**Comment by MaxNoe** [comment]
> I think it already does, but couldn't hurt to add a unit test at least to ensure it doesn't crash

It does not crash, but it also does not use a special color or transparency by default.

**Comment by MaxNoe** [comment]
Checking this, it does not really handle nans well, I will open a PR.

**Pull request merged**
