### PR TITLE
Remove targetio event source and calibrator

### PR DESCRIPTION
**Pull request by MaxNoe**
Now here: https://github.com/cta-observatory/ctapipe_io_targetio

### CODE REVIEW

**Comment by kosack** [comment]
I'll prepare a "before" release now.    Question: what should the new version be? I guess 0.7.0 for this one, since there was significant refactoring of Factories since 0.6.2, but that's somewhat internal, so perhaps 0.6.3 is still ok, and leave 0.7 for the plugin event sources?

**Comment by MaxNoe** [comment]
I don't think it makes sense to do a release now. We are halfway through removing the event sources.

We already removed nectar, lst and sst1m. This is the last one.

So we should either make a release *before* we started to remove any event source, or after we removed all.

**Comment by kosack** [comment]
Ok that's fine then - I think 0.6.2 is fine anyhow, and even though it has a few less event sources, most users will not notice.  I'll wait for the full change for 0.7 then. It's cleaner since its a full overhaul of the I/O.

**Comment by bregeon** [comment]
Well, if I may releases are free, so if someone needs a release se should just do it. :grinning:

**Comment by MaxNoe** [comment]
Eure, but it should make sense. So I would make a release for the last PR we merged before starting to remove the event sources.

**Pull request merged**
