### PR TITLE
Rename ReconstructedContainer.tel_ids -> telescopes, fixes 1953

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by kosack** [comment]
Isn't this less obvious than using tel_ids? There are multiple ways to refer to a telescope:  tel_ids, tel_indices, and tel_names (maybe more).  So just saying  "telescopes" it is not clear which one is expected.  tel_ids makes it clear this is a telescope ID, and not a telescope name, or telescope index.

**Comment by maxnoe** [comment]
@kosack the reasoning here is that e.g. when using the table loader, it is actually a boolean mask, not a list of tel_ids. see #1953

**Comment by maxnoe** [comment]
An alternative would be to just directly fill the mask and call it `tel_mask`?

**Comment by kosack** [comment]
ah, yes, I forgot that there is a translation to a mask when we write it, and then the True values are actually telescope_indices, not tel_ids... so ok, let's keep it as `telescopes`, and the representation of these should be up to the user.  I still like having it a list of tel_ids in the event, since that is somewhat friendlier to read

**Review by kosack — APPROVED** [review]

**Pull request merged**
