### PR TITLE
Bump setuptools and setuptools scm versions

### LINKED ISSUE #2445: Bump setuptools version
I got this error in CI

```
ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61
```

current settings in pyproject.toml are:

```toml
requires = ["setuptools >= 40.6.0", "setuptools_scm[toml]>=3.4"]
```
Can we upgrade to more recent versions?
```toml
requires = ["setuptools>=64", "setuptools_scm>=8"]
```

### PR DESCRIPTION
**Pull request by morcuended**
Versions in the current build settings seem not compatible. Resolves #2445

### CODE REVIEW

**Comment by maxnoe** [comment]
@morcuende, that doesn't seem to fix the build issue. The same error now pops up for eventio.

I will fix it there as well.

**Comment by maxnoe** [comment]
Looking carefully at the log, there seems to be something more amiss here.

THe mamba build shouldn't install eventio via pip. 

It also reports a python version of 3.10 in the 3.11 build.

I think the step "fix PATH for macos" that is also executed on ubuntu runners is the issue

**Comment by maxnoe** [comment]
The pr introducing the "documentation-only" fixes broke this with a wrong logic condition.

**Review by maxnoe — APPROVED** [review]

**Comment by morcuended** [comment]
thanks for the fixes @maxnoe

**Review by kosack — APPROVED** [review]

**Pull request merged**
