### PR TITLE
Additional metadata from pyhessio

### PR DESCRIPTION
**Pull request by morcuended**
Added new parameters from pyhessio to MCHeaderContainer (as asked in [image-extractor#14](https://github.com/cta-observatory/image-extractor/issues/14)):
  - CORSIKA and sim_telarray version
  - energy range of primary particle
  - magnetic field
  - spectral index
  - prod site information

Check [this](https://github.com/morcuended/ctapipe/blob/master/examples/notebooks/Inspect_Provenance_Metadata_Info.ipynb) notebook.

Note that some of the implemented fields (*prod_site_array, prod_site_coord , prod_site_subarray*) are still not retrieving the required information from pyhessio.

### CODE REVIEW

**Comment by Sojourner92** [comment]
Hi Daniel,
Do you have any idea why the three site arrays aren't being retrieved?

**Comment by morcuended** [comment]
Hi Samuel,
No idea. I couldn't find these fields in pyhessio/hessioxxx, probably due to my limited knowledge of them. They must be somewhere in the *runheader* block of simtel files.
I saw you did something similar a few months ago. Do you any idea how we might get this information?

**Comment by kosack** [comment]
The tests currently fail since we don't have a package for the latest pyhessio yet, so when the test-runner installs it, the functions you use are not available.  I'll try to make one shortly. 

We should also add a minimum pyhessio version number in `environment.yml`.

**Comment by Sojourner92** [comment]
Nope, sorry. As far as I recall, it was the case that it wasn't implemented in pyhessio whatsoever, which seems very odd. It's a shame as it'd be an extremely useful feature for machine learning studies with multiple telescopes.

**Comment by GernotMaier** [comment]
Why not adding the possibility the retrieve the full run header? 

e.g. viewcone radius, details on interaction models, wavelength ranges, bunch sizes, how often each shower is used, etc?

Here an example of what was useful in the past:

MC run header:
  Shower program: 1 (CORSIKA) version 6990
  Detector program: 1 (sim_telarray) version 1462392225 (2016-05-04 22:03:45 CEST)
  Shower simulation started 2016-07-11, detector simulation started 2016-07-11
  Observation height: 2150.000000 m
  Number of showers to be simulated: 20000
  Number of arrays per shower: 20
  Core position mode: 1 (circular)
  Core range: 0.000000, 3000.000000 m
  Altitude range: 70.000000 to 70.000000 deg
  Azimuth range: 180.000005 to 180.000005 deg
  Diffuse mode: 1
  Checking units of viewcone parameters: in degrees!
  Viewcone: 0.000000 to 10.000000 deg
  Energy range: 0.003 to 330 TeV
  Spectral index: -2.000000
  B field total: 23.117723 microT, incl.: -22.712710 deg, decl.: 0.000000 deg
  Injection height: -0.001000 km
  Atmospheric density profile: 26
  IACT options: 187
  Low energy model: 2 (URQMD)
  High energy model: 2 (QGSJET)
  Maximum bunchsize: 5.000000
  Wavelength range: 240.000000 to 700.000000 nm
  Details on high-E model: version flag = 3, cross section flag = 3
  This is QGSJET-II.

**Comment by morcuended** [comment]
That would be the best, Gernot. I will work on it.

**Comment by bryankim96** [comment]
Are there any updates on adding these header fields?

**Comment by morcuended** [comment]
Unfortunately, there is nothing new on my side.

**Comment by thomasgas** [comment]
Hi @morcuended!
I was about to make a PR on this in order to add the altitude of the observation site to the `MCHeaderContainer` because by know it is hard-coded: 

- https://github.com/cta-observatory/ctapipe/blob/5849db486586bc94737d171e611cc782bbe927fa/ctapipe/reco/hillas_intersection.py#L324  

- https://github.com/cta-observatory/ctapipe/blob/268c390aaf4111e555a2c5434917c8d7310b5937/ctapipe/reco/ImPACT.py#L250

but I saw that you already started to implement some features. 
Since I would like to add these and other useful informations from the simtel file using pyhessio, would you mind if I continue to implement some features?
@kosack in #466 you said the `MCHeaderContainer` had to be removed: should we complete this task (having a real `MCHeaderContainer` with the informations listed by @GernotMaier) or not?
ideas?
Related to: #500 and #722 from @watsonjj

**Comment by morcuended** [comment]
Sure Thomas, go ahead.

**Comment by thomasgas** [comment]
> Sure Thomas, go ahead.

ok so I'll wait for a reply from @kosack and @watsonjj in order to understand if it is worth the effort or we there a refactoring of the containers in mind which would make such contribution useless.

**Comment by mackaiver** [comment]
We want to put things like observation height into the instrument/subarray configuration.

**Comment by mackaiver** [comment]
Are these fields covered in the pyeventio? @MaxNoe

**Comment by MaxNoe** [comment]
Yes, you could access them from the `mc_runheaders` variable of the `SimTelFile`

**Comment by mackaiver** [comment]
Great. So we can close this. 👍

**Pull request closed without merging**
