### PR TITLE
Use descriptor protocol to mark fields as deprecated

### PR DESCRIPTION
**Pull request by MaxNoe**
Found the solution to the descriptor protocol problem watching this talk: https://www.youtube.com/watch?v=UANN2Eu6ZnM&feature=youtu.be

### CODE REVIEW

**Comment by kosack** [comment]
cool! that sounds like just what we need.

**Comment by kosack** [comment]
Looks like there is still a reference to `DeprecatedField` in `__init__.py`

**Comment by MaxNoe** [comment]
There is a remaining issue here, the default is not set.

**Comment by dneise** [comment]
right and the test did not expect the warning.

**Comment by MaxNoe** [comment]
Also issuing a custom warning would be nice `class DeprecatedFieldWarning(Warning)` (Do not inherit from `DeprecationWarning` as these are filtered by default.

**Comment by dneise** [comment]
Ah I get it .. the default is not set, since the Field is already initialized, when it is handed over to Deprecated ...

**Comment by dneise** [comment]
This is too deep for me, I've got no idea how to fix this.

**Comment by MaxNoe** [comment]
The defaults are set in the `__init__` of container where it loops over all the `fields`. But `fields` now only contain the non-deprecated fields.

**Comment by dneise** [comment]
just saying, I feel unable to do this ...

**Comment by MaxNoe** [comment]
To be included in the introduction of typed fields in the next version

**Comment by watsonjj** [comment]
Related PR/issue?

**Comment by MaxNoe** [comment]
Non yet. This was just a refactoring I had planned.

**Comment by MaxNoe** [comment]
Getting rid of the deprecations is probably better than improving how we mark things as deprecated.

**Pull request closed without merging**
