### PR TITLE
Make gain_selector a trait of SimTelEventSource, fixes eventsource plugins

### PR DESCRIPTION
**Pull request by MaxNoe**
The dl1 tool had a gain_selector member / trait that it always passed to the `EventSource`, although this is an implementation detail of the `SimTelEventSource`, not a part of the public API of `EventSource`.

This fixes it by making the `gain_selector` a trait of the `SimTelEventSource`, thus bringing the API of the SimTelEventSource back in line with the base class.

### CODE REVIEW

**Comment by watsonjj** [comment]
Maybe this is nicer. However, it does remove the ability to configure the `GainSelector` in a script before it is passed to the `SimtelEventSource`.

**Comment by MaxNoe** [comment]
> Maybe this is nicer. However, it does remove the ability to configure the GainSelector in a script before it is passed to the SimtelEventSource.

No, you can configure it by setting the proper configuration through the traitlets system. This is how it should be done.

It's not about being nicer, it's about having the correct public API, so the EventSources are interchangable

**Comment by MaxNoe** [comment]
Actually, this goes a bit deep, but let's leave it here for that.

This pattern of passing in pre-configured components to other components is happening more often than just here, e.g. see #1392 .

This prevents configuring these components through the config system, which makes the command line tools much less powerfull than they could (and probably were meant to) be.

I'll open other PRs for the rest

**Comment by MaxNoe** [comment]
The big issue here was, that we introduced an incompatible API for the `SimTelEventSource` compared to the one of `EventSource`, that should not happen.

**Pull request merged**
