### PR TITLE
Chunked table loader

### PR DESCRIPTION
**Pull request by maxnoe**
Needs #1934

### CODE REVIEW

**Comment by kosack** [comment]
It might be a nicer API to have the division into chunks happen inside, rather than by the user, e.g. rather than have a start/stop, allow the user to specify a `chunk_size` (or a `n_chunks`):

```py3
loader = TableLoader(..., chunk_size=1000)

for chunk in  table_loader.read_subarray_events():
    do_stuff(chunk)
```
or perhaps better, put the chunking options in `read_subarray_events()` and `read_telescope_events()` themselves:

```py3
for chunk in  loader.read_subarray_events(chunk_size=1000):
    do_stuff(chunk)
```

in that case, read_subarray_events returns a *generator* if chunk_size is non-zero, and you can even do things like:

```py3
map( do_stuff, loader.read_subarray_events(chunk_size=1000))
```

**Comment by maxnoe** [comment]
> It might be a nicer API to have the division into chunks happen inside, rather than by the user, e.g. rather than have a start/stop, allow the user to specify a chunk_size (or a n_chunks):

Yes, this is planned (the reason this is still a draft). I only managed the basic building blocks yesterday in an "how many off by one errors can you do in two hours" session

**Review by LukasNickel — APPROVED** [review]

**Review by kosack — APPROVED** [review]
Very nice!  I did a quick check to make sure the memory is properly handled, and it looks great:

image

**Comment by kosack** [comment]
perhaps also mention the chunked versions in the docstring, or in the general docs.  

Also, a nice example might be making a histogram over all chunks:

```py3
from ctapipe.utils import Histogram

e_dist = Histogram(nbins=[100], ranges=[[-2,2]], axis_names=['$\log10 E_{true}$',])

for chunk in tqdm(loader.read_subarray_events_chunked(50_000)):
    e_dist.fill(np.log10(chunk['true_energy']))

e_dist.draw_1d()
```
image

**Review by kosack — APPROVED** [review]

**Pull request merged**
