### PR TITLE
Support different frames for set_line_hillas

### PR DESCRIPTION
**Pull request by StFroese**
Works now for other frames, e.g. `EastingNorthing`
Screenshot 2022-11-23 at 16 39 09

### CODE REVIEW

**Review by kosack — APPROVED** [review]

**Comment by kosack** [comment]
Note that you seem to to have selected the LaPalma alpha telescope id list but applied it to the Paranal array, so that is why you have such a strange-looking array :-)  You should use the Paranal-alpha list!

**Comment by kosack** [comment]
Also, I notice there is still a bug: the points for the line are not correctly transformed

**Comment by StFroese** [comment]
Oh your right

**Comment by StFroese** [comment]
> Note that you seem to to have selected the LaPalma alpha telescope id list but applied it to the Paranal array, so that is why you have such a strange-looking array :-) You should use the Paranal-alpha list!

I didn't select anything (as far as I know). It's just the file:
```python
source.subarray.info()
```
```
Subarray : Paranal-prod6_1-11,19,35
Num Tels : 13
Footprint: 0.59 km2

      Type       Count  Tel IDs  
---------------- ----- ----------
  LST_LST_LSTcam     4 1-4       
MST_MST_FlashCam     9 5-11,19,35
```

**Pull request merged**
