### PR TITLE
Calibration arguments

### PR DESCRIPTION
**Pull request by watsonjj**
Update to the calibration argument parsing, making it more flexible so individual cameras can specify their own arguments they require for calibration.

### CODE REVIEW

**Comment by kosack** [comment]
For options and arguments, please use the `ctapipe.core.Container` and `ctapipe.core.Tool` functionality and not `argparse` or a custom parser.  That way all modules will work the same and there is a single configuration format.

**Comment by kosack** [comment]
Another major problem is that the configuration parameters should *not* be passed around as dicts, since those cannot be validated or checked, and that can lead to unexpected behavior.  This is confusing to users and hard to debug.

HEre is an example of how it should work: rather than having a master function like calibrate event that takes all parameters, break it down in to specific tasks. For instance trace integration should have a class hierarchy with all intergrator types (`Integrator`, `SimpleWindowIntegrator`, etc), adn those should handle integration parameters like the window size, etc.

Any options to a function must be explicit named parameters with defaults if they are known:
```python
def calibrate_event(event, integrator=DefaultIntegrator(window=5)):
    ...
```
Use a `Component` as the base class for any algorthms that require several functions that share parameters:

```python
from traitlets import Integer
class WindowIntegrator(Component):
     window_size = Integer(default_value=6, help='integration window size in samples')\
                                          .tag(config=True)

    def integrate(samples):
         ...
```

See the `ctapipe.core.Container` docs for more examples (for some reason the example codes doesn't appear in the sphinx output, but it's in the code itself - I'll fix that soon)

**Comment by kosack** [comment]
I've created an issue #179 to track this, since it's  a major change, but I'll probably just accept this pull request for now, and leave the refactoring for later.

**Comment by watsonjj** [comment]
Hi Karl. Thanks, I was hoping you would be okay with that.

I mostly follow what you have said, and I would like to implement it. This is the first time I've looked into the application of `ctapipe.core.Container` and `ctapipe.core.Tool`, and it will take a little time to understand how to develop the calibration to that level.

**Pull request merged**
