### PR TITLE
make calibration an option in read_hessio_single_tel

### PR DESCRIPTION
**Pull request by kosack**
- needs update to pyehssio to fix reading the calib coeffs

### CODE REVIEW

**Comment by jacquemier** [comment]
Could you confirm that calibration error in pyhessio is result of get_calibration function ?

I have just checked and I did not find where low gain data and high gain data are interlaced.

**Comment by kosack** [comment]
it's a good question - is the correct way to read the pedestals and gains for channel 0 the following:

```python
peds = pyhessio.get_pedestal(tel_id)[0]
gains = pyhessio.get_calibration(tel_id)[0]
```

If so, there seems to be an issue.  If you plot the peds or gains that you get in that case, you end up with values that are in 2 distributions:  `plot(peds,gains)`:

pedsgains

The two gain values and two pedestal values look like what you would get if you were looking at a mixture of the low and high-gain channels.

**Comment by kosack** [comment]
The effect on an image is that every other pixel looks like it is bright or dark, which implies some mixing. It looks like an indexing error (e.g. a 972x2 array is being read as a 2x972 array)

**Comment by kosack** [comment]
It seems only to be an issue for prod3. In Prod2, I get the following for a single camera, which looks correct (there is a single distribution, not two):
pedsgains_prod2

So it could be that the data layout changed between the prods?

**Comment by kosack** [comment]
I'll open an issue...

**Comment by jacquemier** [comment]
Did you use same pyhessio version for PROD2 and PROD 3 ?
What's I know for sur, iis that there was indeed a bug in pyhessio.
I have just corrected/commited and merged.

**Pull request merged**
