### PR TITLE
Ci pipeline for ctao sonarqube

### PR DESCRIPTION
**Pull request by kosack**
another attempt

### CODE REVIEW

**Comment by kosack** [comment]
I need to figure out how to incorporate the test coverage here - this should run after the test job, so that the coverage info is available, so probably has to be in the same pipeline as the tests

**Comment by maxnoe** [comment]
> I need to figure out how to incorporate the test coverage here - this should run after the test job, so that the coverage info is available, so probably has to be in the same pipeline as the tests

You need to declare the coverage xml report as an artifact, which will make it available to the sonarqube stage

**Comment by maxnoe** [comment]
pytest says: https://github.com/cta-observatory/ctapipe/actions/runs/6890858501/job/18752250379?pr=2456#step:10:152

```
---------- coverage: platform linux, python 3.10.13-final-0 ----------
Coverage XML written to file coverage.xml
```

But codecov and sonarqube don't see the file: https://github.com/cta-observatory/ctapipe/actions/runs/6890858501/job/18752250379?pr=2456#step:11:33

>  [2023-11-16T12:50:52.721Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`

**Comment by maxnoe** [comment]
I am closing this in favor of #2463 since I am quite convinced now that it won't properly work in our current setup.

**Pull request closed without merging**
