### PR TITLE
Use lts regression instead of siegel slopes for timing parameters

### PR DESCRIPTION
**Pull request by MaxNoe**
Speedup ca. 5x.

This should be the same algorithm as used by EventDisplay and Mars.

Unfortunately, I could not find a good implementation for python, so I implemented it myself after the reference given in the bibliography.rst

### CODE REVIEW

**Comment by MaxNoe** [comment]
Here is an example of the result:

lts_regression

**Comment by MaxNoe** [comment]
The tests fail because they tested for exact results of the old algorithm, it is not surprising that the values changed now that another algorithm is used.

**Comment by kosack** [comment]
The main test that is failing here is the two-pass window sum integration (which is the algorithm used in MARS), which uses the timing slope to recompute the integration windows. 

In the test it makes a toy model for the "true" result and tries to reconstruct it, but now gets a worse result than before. Do we understand why? In this simple case, if the timing slope is correct, the answer should be very close to the truth value. So if we increase the tolerance, it would be good to be careful that it is correct to do so.  @HealthyPear how did you choose the tolerance for this test (rtol=0.07) ? Is it overly conservative?

**Comment by HealthyPear** [comment]
> @HealthyPear how did you choose the tolerance for this test (rtol=0.07) ? Is it overly conservative?

No real reason: actually I even made it stricter than the tests just above, which use 0.1 ....

**Comment by MaxNoe** [comment]
I relaxed the requirement to 0.1 like in the other tests, test should be passing now.

It is also unsurprising that this algorithms performs slightly worse in the absence of outliers, since it uses fewer points, so the variance will be higher.

**Comment by kosack** [comment]
> It is also unsurprising that this algorithms performs slightly worse in the absence of outliers, since it uses fewer points, so the variance will be higher.

Is that going to be a problem for small images where there are only 3-4 points to fit?

**Review by kosack — APPROVED** [review]

**Comment by MaxNoe** [comment]
> Is that going to be a problem for small images where there are only 3-4 points to fit?

How well are all the other algorithms handling events with 3-4 pixels in the shower? 

I don't expect this fitting to be any worse than other parts of the pipeline.
The fits also depends on the shower axis estimation, which will not be really reliable on 3-4 pixels in the first place.

**Review by HealthyPear — APPROVED** [review]

**Pull request merged**
