### PR TITLE
Start working on reading adc_sums

### PR DESCRIPTION
**Pull request by maxnoe**
These seem to be raw adc sums that need to be calibrated, we need to figure out how to correctly convert to pe.

They also have both gains, so we also somehow need to perform a gain selection.

Maybe @ParsonsRD knows? If not I'll contact konrad

### CODE REVIEW

**Comment by maxnoe** [comment]
This is intended  to fix #1777 

If we don't want this, we should close #1777 as "won't fix"

**Comment by kosack** [comment]
> This is intended to fix https://github.com/cta-observatory/ctapipe/issues/1777

Ah, right, in the raw data, this has no useful meaning (it's just the full sum of the waveform), however, for DST-style output (which is closer to DL1), it's the DL1 image.   So if we want to use it, we have to do the same calibration as for the simulated waveform, but using the integrated  pedestal.  But in that case the EventSource should then also report that it outputs DL1_IMAGE information, and not DL0 since the waveforms are no longer there.  

Is it worth supporting that? Not sure - do we have a lot of Simtel DST data where we don't already have the raw data?

**Comment by maxnoe** [comment]
> Is it worth supporting that? Not sure - do we have a lot of Simtel DST data where we don't already have the raw data?

Have? No. I don't think so. But I think for data storage reasons, @ParsonsRD uses it in the ImPACT training workflow.

**Comment by maxnoe** [comment]
Closing for now. Will reopen if need arises and we have a solution.

**Pull request closed without merging**
