### PR TITLE
detect ctapipe_io_ plugins in eventsource factory

### PR DESCRIPTION
**Pull request by dneise**
preparation for io plugins containing dedicated EventSources

### CODE REVIEW

**Comment by kosack** [comment]
thanks for starting this! Once we have this interface, we can then require that the tests for external readers are in those readers' repos, rather than in ctapipe itself.

**Comment by MaxNoe** [comment]
Why was this closed?

**Comment by dneise** [comment]
Ah .. sorry, should have explained it.
So .. somehow .. I did not research how... this already made its way into the master:

https://github.com/cta-observatory/ctapipe/blob/master/ctapipe/io/__init__.py#L10

**Comment by dneise** [comment]
So this is not needed anymore

**Comment by dneise** [comment]
Here I am trying out if it works
https://github.com/cta-observatory/ctapipe/pull/981

**Comment by MaxNoe** [comment]
See:
blame

**Comment by dneise** [comment]
yeah .. but I am not aware how this stuff ended up in that PR it was unrelated... but well .. it did not harm.

**Pull request closed without merging**
