### PR TITLE
Enable field inheritance for containers, add test, fixes #648

### LINKED ISSUE #648: Containers do not inherit fields

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by dneise** [comment]
Do you also want to allow:
```
class ContainerA(Container):
    a = Field('a')
    great_field = Field(None)
class ContainerB(Container):
    a = Field('b')
    awesome_field = Field(None)
class ContainerC(ContainerA, ContainerB):
    c = Field(None)
```
???

**Comment by MaxNoe** [comment]
I would, python does not.

Python does not allow inheritance from two classes who share the same base class

**Comment by dneise** [comment]
Ok. thanks

**Comment by kosack** [comment]
Seems fine to me, though so far we do not have containers inheriting from others since we used composition over inheritance, since they are supposed to be similar to database schema definitions,  but perhaps we will in the future (e.g it might be nice to have all containers that have an `event_id` and `time` to have a common base to avoid some duplication). In any case it should probably work sensibly.

**Comment by kosack** [comment]
One question: does this slow down construction much? e.g. does it make the concerns of #642  worse?

**Comment by MaxNoe** [comment]
@kosack 

This code runs once at class definition. (It is in the metaclass)

**Pull request merged**
