### PR TITLE
rename hessio_event_source to simtelarray_event_source?

### PR DESCRIPTION
**Pull request by kosack**
More efforts to clarify some of the code:
------------------------------------

- to avoid confusion renamed the event source to be more clear about what data it applies to (not only HESS)
- also changed HessioFileReader → SimTelArrayFileReader
- also fixed small bug where the event source generator doesn't exit if
a single event is requested (causing some tests to fail due to an
unclosed file)

### CODE REVIEW

**Comment by watsonjj** [comment]
Should all references to "hessio" be changed to "simtelarray"?

**Comment by kosack** [comment]
> Should all references to "hessio" be changed to "simtelarray"?

It's just a proposal, but I guess so.  The confusion is that this is really a reader for EventIO files from SimTelArray, with the particular EventIO dialect being HESSIO (called that for historical reasons). So the original name is not incorrect, but is just perhaps confusing for users who might think it is HESS-specific.  Of course once we have an official new format for CTA, I would guess *simtelarray* will be modified to use it, so then this reader may not be correct anymore (for example we might switch to the updated format called IACTIO, which is not the same as HESSIO, or even something totally different).   For that reason, I wasn't sure of the best name...   We could also go with `eventio_event_source`

**Comment by kosack** [comment]
p.s. I did rename the FileReader subclass in this PR as well, which is now SimTelArrayFileReader

**Comment by kosack** [comment]
I thing in the end we'll keep it as is , to avoid confusion

**Pull request closed without merging**
