### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by kosack** [comment]
the build is failing only due to travis-sphinx (so unrelated).

Also, Is it normal to get so many `UnknownPixelShapeWarnings`?

**Comment by MaxNoe** [comment]
> Also, Is it normal to get so many UnknownPixelShapeWarnings?

Yes, since a few tests still open the prod2 file, each time this file is opened, this warning is emitted, since prod2 file do not save the pixel shape.

**Comment by kosack** [comment]
Ah, ok then we can just accept that until we update the tests to a more modern file

**Comment by kosack** [comment]
For the build failure, see #1010

**Comment by MaxNoe** [comment]
I fixed it by requiring nbconvert > 5.4 which works with tornado 6

**Comment by MaxNoe** [comment]
Merge?

**Pull request merged**
