### PR TITLE
Use sphinx-changelog

### PR DESCRIPTION
**Pull request by maxnoe**
Replace custom solution with using sphinx-changelog, this also works on readthedocs and means we get the changelog previewed in the "latest" docs.

### CODE REVIEW

**Comment by Tobychev** [comment]
Results look identical between the CI version and latest, so I'm confused about what you mean by this "we get the changelog previewed"?

I can spot one behaviour change between the [CI version](https://ctapipe--2657.org.readthedocs.build/en/2657/changelog.html#ctapipe-v0-23-0-2024-11-18) and [prod](https://ctapipe.readthedocs.io/en/stable/changelog.html): when you scroll all the way up on the CI the right hand side content menu doesn't collapse down to one line per release like it does on prod.

**Comment by maxnoe** [comment]
> Results look identical between the CI version and latest, 

That's because we haven't merged anything yet since the last tag

**Review by kosack — APPROVED** [review]

**Comment by maxnoe** [comment]
But this branch is not updated with respect to merge

**Review by Tobychev — APPROVED** [review]

**Comment by maxnoe** [comment]
You can now see it here: https://ctapipe.readthedocs.io/en/latest/changelog.html @Tobychev

**Pull request merged**
