### PR TITLE
remove unused dependencies in environment.yml

### PR DESCRIPTION
**Pull request by vuillaut**

### CODE REVIEW

**Comment by MaxNoe** [comment]
Could you remove those also from the test environments?

**Comment by vuillaut** [comment]
There is also `graphviz` for which I don't see any reference anywhere.
Do you know what's it used for?

**Comment by thomasgas** [comment]
iminuit is used by ImPACT, so I would not remove it from the environment.

**Comment by MaxNoe** [comment]
> There is also graphviz for which I don't see any reference anywhere.
Do you know what's it used for?

This is used to, spoiler alert, visualize graphs. Scikit-learn e.g. can export drawings of decision trees using graphviz, but that is an optional dependency.

**Comment by MaxNoe** [comment]
@thomasgas  Also by the muon code it seems

**Comment by vuillaut** [comment]
> iminuit is used by ImPACT, so I would not remove it from the environment.

iminuit was listed twice

**Comment by MaxNoe** [comment]
> iminuit was listed twice

It's really important !!!111!

**Comment by MaxNoe** [comment]
Maybe we can just `:sort` these?

**Comment by vuillaut** [comment]
> Maybe we can just `:sort` these? Looks like they were at some point.

No idea how to do that 😅

**Comment by MaxNoe** [comment]
> You mean automatically enforce sorting when a dep is added ?

No, just this once, not overengineering her :rofl:   

`:sort` is the vim command to sort selected rows alphabetically :wink:

**Comment by kosack** [comment]
> graphviz

It's used in the documentation by Sphinx when it generates class diagrams (they don't get rendered if not installed), so perhaps keep it in the test envs, but not the main one since it's not required.

**Comment by kosack** [comment]
For a future task, I would like to avoid having to edit setup.py, enviromnent.yml, and the conda package def ever time a requirement changes, so at least in the conda env I will start to use the Jinja2 template stuff more (you can automatically extract dependences from setup.py).  Perhaps the same can be done for these yml files. 

For example see the CookieCutter template here (which has templates embedded in templates, but you can basically get the idea if you look at the sections marked "raw"): https://github.com/conda/cookiecutter-conda-python/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/conda.recipe/meta.yaml

**Comment by MaxNoe** [comment]
Conda keeps on improving interoperability with pip, so maybe we can soon do `conda install .` and it will install everything using conda.

**Comment by kosack** [comment]
In related news: I created a new conda package recipe that so far handles this much better than before, so I don't need to do manual updating.   https://github.com/cta-observatory/cta-conda-recipes/blob/master/ctapipe-0.7.conda/meta.yaml

**Comment by vuillaut** [comment]
So, regarding the discussion and in the preparation of the v0.7 release, should I modify this PR? Is it superseded by @kosack changes?

**Comment by MaxNoe** [comment]
@vuillaut 

@kosack did not make any changes, I think the issue #1113 was just creted for further discussion after this PR

**Comment by vuillaut** [comment]
> @vuillaut
> 
> @kosack did not make any changes, I think the issue #1113 was just creted for further discussion after this PR

I think you mean #1114

**Comment by vuillaut** [comment]
Yes I think he made these changes:
> I'm now using conda-build's jijja2 templating to extract the list of ctapipe dependencies from setup.py and transfer them automatically to the build recipe

So my question is, is this PR now useless and should be closed?

**Comment by MaxNoe** [comment]
I think these are independent changes to make the creation of the conda 
packages easier.

Nothing directly linked to this.

Am 29. Juli 2019 18:29:07 schrieb Thomas Vuillaume <notifications@github.com>:

**Comment by kosack** [comment]
No, sorry for the confusion - this PR is fine and should be merged. I just wanted to mention that I am cleaning up the dependencies in general. We can do a different PR for setup.py, and then I will make the release once it seems ok and this PR is also merged.

**Comment by kosack** [comment]
unless you want to also clean up setup.py in this PR (which is also fine , but not required)

**Comment by kosack** [comment]
Still waiting for another approval to merge this

**Comment by thomasgas** [comment]
I haven't followed the discussion a lot, so I have a question: merge or not? I'm ok with this PR, unless I'm missing something.

**Comment by vuillaut** [comment]
> I haven't followed the discussion a lot, so I have a question: merge or not? I'm ok with this PR, unless I'm missing something.

It's basically just waiting for another approval (summer break...).

**Comment by thomasgas** [comment]
> > I haven't followed the discussion a lot, so I have a question: merge or not? I'm ok with this PR, unless I'm missing something.
> 
> It's basically just waiting for another approval (summer break...).

There you go ;)

**Pull request merged**
