### PR TITLE
Add Tool and Component base class

### PR DESCRIPTION
**Pull request by kosack**
Purpose:
------------

**Use case 1**: *Developer wants to writes a CLI application that can be launched by a user that provides common command and parameter handling, logging, and other standard features.*

**Use Case 2**: *The user launches an application from the command-interpreter (bash, etc), or via a Python script by instantiating and configuring it within python.*

Implementation
---------------------

Added preliminary `Tool` (application) and `Component` (worker, module) base classes to `ctapipe.core`, based on `traitlets.config.Configurable`, along with documentation and examples. This will eventually replace the configuration module, and will implement the *provenance* meta-data model.  

The ``ctapipe-dump-triggers`` tool (code in ``ctapipe/tools/dump_triggers.py``) was also updated to use this as a complete example of making a command-line tool, and other example code will be modified to match once this is stable. 

Please take a look and give comments on whether or not this meets expectations.  

### Some features:

* configuration variables are easy to define for for Components and Tools, and can be read/written to JSON or python scripts, or to FITS headers (via existing code in the `ctapipe.configuration` module)
* configuration parameters can be delegated to command-line parameters
* some virtual functions for starting up, running, and stopping a command-line tool (batch tool)
* logging is setup and linked from child to parent automatically for all Components and Tools (the Tool additionally provides config options to change the log level and format).

### Some missing features to think about:

* command-line parameters are so far all named, with no positional parameter support (due to this feature missing in `traitlets.config.Application`, but we could add it ourselves in the future. This essentially means that one needs to run ``tool --myoption=6 --infile filename.fits`` instead of ``tool --myoptoin=6 filename.fits``
* no definition of how do do an event loop is made (this is left up to the developer).  This is probably good for flexibility. We could imagine in the future a ``ZMQTool`` vs ``BatchTool`` that provide different implementations though.

### CODE REVIEW

**Comment by jacquemier** [comment]
I'll take a look and give you feedback. 

Cheers, Jean 

| De: "Karl Kosack" <notifications@github.com>
| À: "cta-observatory/ctapipe" <ctapipe@noreply.github.com>
| Envoyé: Jeudi 30 Juin 2016 15:24:27
| Objet: [cta-observatory/ctapipe] Add Tool and Component base class (#135)

| Purpose:

| Use case 1 : Developer wants to writes a CLI application that can be launched by
| a user that provides common command and parameter handling, logging, and other
| standard features.

| Use Case 2 : The user launches an application from the command-interpreter
| (bash, etc), or via a Python script by instantiating and configuring it within
| python. Implementation

| Added preliminary Tool (application) and Component (worker, module) base classes
| to ctapipe.core , based on traitlets.config.Configurable , along with
| documentation and examples. This will eventually replace the configuration
| module, and will implement the provenance meta-data model.

| The ctapipe-dump-triggers tool (code in ctapipe/tools/dump_triggers.py ) was
| also updated to use this as a complete example of making a command-line tool,
| and other example code will be modified to match once this is stable.

| Please take a look and give comments on whether or not this meets expectations.
| Some features:

|    * configuration variables are easy to define for for Components and Tools, and
|    can be read/written to JSON or python scripts, or to FITS headers (via existing
|     code in the ctapipe.configuration module)
|     * configuration parameters can be delegated to command-line parameters
|    * some virtual functions for starting up, running, and stopping a command-line
|     tool (batch tool)
|    * logging is setup and linked from child to parent automatically for all
|    Components and Tools (the Tool additionally provides config options to change
|     the log level and format).
| Some missing features to think about:

|    * command-line parameters are so far all named, with no positional parameter
|    support (due to this feature missing in traitlets.config.Application , but we
|    could add it ourselves in the future. This essentially means that one needs to
|    run tool --myoption=6 --infile filename.fits instead of tool --myoptoin=6
|     filename.fits
|    * no definition of how do do an event loop is made (this is left up to the
|    developer). This is probably good for flexibility. We could imagine in the
|     future a ZMQTool vs BatchTool that provide different implementations though.

| You can view, comment on, or merge this pull request online at:

| https://github.com/cta-observatory/ctapipe/pull/135 Commit Summary

|     * started to add a Tool and Component class
|     * Tool and Component classes now can be started/stopped
|     * documentation updates
|     * added basic useage docs for Tool
|     * fix doc problems
|    * Merge remote-tracking branch 'cta-observatory/master' into
|     add_application_class
|     * update to use core.Tool
|     * modify ctapipe-dump-triggers to use Tool
|     * add n_trig column
|     * use logger
|     * add Tool alias for log_level always
|     * improve Tool class and DumpTriggerTool example
|     * keep an is_initialized flag in Tool
|     * add tests and cleanup
|     * add test for Tool
|     * doc updates
|     * fix doc error
|     * more descriptions in example notebook
|     * example of json loading
|     * rename initialize() to setup()
|     * added docs for tools module
|     * doc updates
|     * more doc updates and fixes
|     * remove test_frames which shouldn't be in tools/tests
|     * remove logging config override
|     * moved configuration/json2fits code to utils
|     * add test
| File Changes

|     * A config_to_fits.fits (1)
|     * M ctapipe/configuration/__init__.py (1)
|     * M ctapipe/core/__init__.py (160)
|     * A ctapipe/core/component.py (61)
|     * A ctapipe/core/container.py (146)
|     * A ctapipe/core/tests/test_component.py (24)
|     * M ctapipe/core/tests/test_container.py (2)
|     * A ctapipe/core/tests/test_tool.py (23)
|     * A ctapipe/core/tool.py (153)
|     * M ctapipe/tools/camdemo.py (7)
|     * M ctapipe/tools/dump_triggers.py (151)
|     * D ctapipe/tools/tests/test_frames.py (4)
|     * M ctapipe/utils/__init__.py (1)
|     * R ctapipe/utils/json2fits.py (11)
|     * R ctapipe/utils/tests/test_json_2_fits.py (14)
|     * M ctapipe/visualization/mpl.py (30)
|     * M docs/calib/index_camera.rst (4)
|     * A docs/core/corediagram.dot (24)
|     * M docs/core/index.rst (26)
|     * M docs/getting_started/index.rst (2)
|     * M docs/index.rst (1)
|     * M docs/tools/index.rst (66)
|     * A examples/notebooks/Tools.ipynb (644)
|     * A examples/notebooks/Tools.json (4)
|     * A json_to_fits.fits (1)
|     * M setup.cfg (5)
|     * A test.h5 (0)
|     * A trig.csv (1)
|     * A trig.h5 (0)
| Patch Links:

|     * https://github.com/cta-observatory/ctapipe/pull/135.patch
|     * https://github.com/cta-observatory/ctapipe/pull/135.diff

| —
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly, view it on GitHub , or mute the thread .

**Comment by jacquemier** [comment]
General comments after some tests:
- It is efficient and quite simple to use.
- All previous config system functionalities are present.

Some remarks:
- Default log level is WARNING (python standard ?). So logger.info() messages are not print. Should we set default level to INFO by default ?
- We could add a json config file example and used it in DumpTriggersTool example.
- If --config flag is pass with a config file that does not exist, no error is returned or displayed.
- aliases is a concept a bit difficult. Peharps we can refer to traitset do:
http://traitlets.readthedocs.io/en/stable/config.html#aliases

Now I will reimplement zmq pipeline with this configuration system.

**Comment by jacquemier** [comment]
Class based on Tool class cannot define a `__init__(self) `method. Otherwise, it produce a traitlets error

```
...
 File "/home/jacquem/anaconda3/envs/cta/lib/python3.5/site-packages/traitlets/config/application.py", line 295, in print_alias_help
    cls = classdict[classname]
KeyError: 'Pipeline'

```

**Comment by jacquemier** [comment]
I need to configure 2 instances of same class (Component Based) which need differents configurations 
This is what I found in documentation.

>  Furthermore, if two instances need to be configured differently, they need to be
> instances of two different classes. While this model may seem a bit restrictive, we have found that it expresses most
> things that need to be configured extremely well. However, it is possible to create two instances of the same class that
> have different trait values. This is done by overriding the configuration.

But I did not find any documentation on : How to overriding the configuration ?

**Comment by kosack** [comment]
Yes, I think it needs some work, but should be ok for a start. I will try to change the default log level to INFO and make some documentation on how to have 2 classes: for now, I think you have to make a new subclass to have two of the same one, which isn't very nice.  It may be solvable by having a "name" parameter for each Tool/Component that can be different for different versions of the same class (that is what ROOT does, for example)

**Comment by jacquemier** [comment]
For subclasses of Component class.
Call to Component's init method is mandatory for using self.log.

    def __init__(self):
        super().__init__(parent=None)
Perhaps we can add this to Component documentation

**Pull request merged**
