### PR TITLE
Add pix_size to CameraGeometry, read in simtel eventsource

### PR DESCRIPTION
**Pull request by MaxNoe**
- [ ] IO
- [ ] Use it where appropriate

### CODE REVIEW

**Comment by kosack** [comment]
Can you explain why this is needed?  It's easy to calculate from the pix_area and pix_type

**Comment by MaxNoe** [comment]
I just went through the open issues: #1019 

Why not set it directly from the simtelfile?

**Comment by kosack** [comment]
> Why not set it directly from the simtelfile?

We only use the pix_size for plotting, so it was just to try to limit the number of things to keep track of in a camera definition file.   Also, the size of the pixel as a diameter has little meaning in reality, since there are Winston cones which means the sensitive area of a "pixel" is a hexagon (for hex cameras), and can be larger than the size of the phototube. For a hexagon, what is the use of defining a diameter? An area gives you the same information, and more accurately.

**Comment by MaxNoe** [comment]
ok, I see it's redundant and area more what's needed

**Pull request closed without merging**
