### PR TITLE
Add support for hillas parameters in TelescopeFrame to CameraDisplay

### PR DESCRIPTION
**Pull request by maxnoe**
- [x] test

### CODE REVIEW

**Review by LukasNickel — APPROVED** [review]

**Comment by kosack** [comment]
I imagine this also has to be fixed in the Bokeh version?

**Comment by maxnoe** [comment]
> I imagine this also has to be fixed in the Bokeh version?

Yes indeed. I will make another PR for the bokeh one

**Comment by maxnoe** [comment]
Thinking about it, I think it makes sense to do it together here...

**Comment by maxnoe** [comment]
Done

**Review by kosack — APPROVED** [review]

**Review by LukasNickel — APPROVED** [review]

**Pull request merged**
