### PR TITLE
Muon features

### PR DESCRIPTION
**Pull request by MaxNoe**
This is a new PR with basically the same features as in #171, please refer to there for the first results tested on LST Mono MC data.

This only adds more docs and moved the functions to the image module.

We now have to methods to perform the kundu_chaudhuri fit and two to estimate optical efficiency.

### CODE REVIEW

**Comment by AMWMitchell** [comment]
Hi Max,

I already merged your pull request so that your code is in the branch; however, you will need to modify your code slightly into a format consistent with the base classes "intensity_fitter.py" and "ring_fitter.py". Parameter outputs of the ring and intensity fitting procedures should fill the "MuonRingParameter" and "MuonIntensityParameter" container classes in io/containers.py

This is due to the efforts last week to ensure that all muon algorithms developed can be tested in a common way within the muonmaster branch, before we decide what should be merged to the master branch. There will be an email soon explaining all this. 

Thanks!

**Comment by MaxNoe** [comment]
I do not think that code related stuff should be discussed in emails. 

You should create an issue and give it the 'Muon' label.

**Comment by AMWMitchell** [comment]
I think you misunderstood - the email is for the cta muon mailing list, as information for all muon code developers, informing them how this will take place. All specific code discussions will of course take place on github.

**Comment by MaxNoe** [comment]
Ah, OK. Perfect.

**Pull request merged**
