### PR TITLE
make pyhessio not necessary for normal users

### PR DESCRIPTION
**Pull request by dneise**
pyhessio is nowadays only needed to verify pyeventio works correctly. So some users might not even want to install it...

### CODE REVIEW

**Comment by dneise** [comment]
Any opinions here from non pyeventio developers?

**Comment by thomasgas** [comment]
> Any opinions here from non pyeventio developers?

So pyhessio would be installed only if one develops something and have to run tests which will then will require to download pyhessio, right?
If so, I'm ok for dropping the installation of pyhessio.

**Comment by dneise** [comment]
Not exactly.

The tests can still be run also without having pyhessio installed. Just the 4 tests which explicitely need pyhessio will automatically be skipped for people (users or developers who do not develop something which needs pyhessio) who do not have pyhessio installed.

This automatic skip of tests is done using pytest.importorskip().

So any user can still: 
 - install ctapipe and
 - perform the tests using pytest.

They just do not need to have pyhessio installed and also do not need to alter their stack size in order to make pyhessio work.

**Comment by dneise** [comment]
Thus PR might have helped in cases like #952

**Comment by thomasgas** [comment]
Ok now I understood the skip in pytest. So i definitely agree!

**Comment by dneise** [comment]
On travis we do still install pyhessio in order to stay sure that pyeventio and pygessio deliver the exact same results for selected simtel files.

These tests are needed to gain trust into pyeventio, but strictly speaking they should not be part of ctapipe, but of pyeventio.

**Pull request merged**
