### PR TITLE
Update mailmap

### PR DESCRIPTION
**Pull request by MaxNoe**
Shortlog now looks like this:

```
  1485  Karl Kosack <karl.kosack@cea.fr>
   525  Jason Watson <jason.watson@desy.de>
   265  Daniel Parsons <dparsons@lfs2.mpi-hd.mpg.de>
   235  Jean Jacquemier <jacquem@lapp.in2p3.fr>
   217  Maximilian Nöthe <maximilian.noethe@tu-dortmund.de>
   200  Tino Michael <tino.michael@cea.fr>
    76  Alison Mitchell <alison.mitchell@mpi-hd.mpg.de>
    68  Dominik Neise <neised@phys.ethz.ch>
    59  Christoph Deil <Deil.Christoph@gmail.com>
    52  Justus Zorn <justus.zorn@desy.de>
    34  Samuel Timothy Spencer <sojourner92@gmail.com>
    29  Raquel de los Reyes <reyes@mpi-hd.mpg.de>
    28  Franca Cassol <cassol@cppm.in2p3.fr>
    23  Kai Brügge <kai.bruegge@tu-dortmund.de>
    16  Michele Mastropietro <michele.mastropietro@gmail.com>
    14  Thomas Vuillaume <thomas.vuillaume@lapp.in2p3.fr>
    13  Jeremie DECOCK <jd.jdhp@gmail.com>
    12  Tarek Hassan <tarek.hassan@desy.de>
    12  Wrijupan Bhattacharyya <wrijupan.bhattacharyya@desy.de>
    11  Abelardo Moralejo Olaizola <moralejo@ifae.es>
    11  Francesco Visconti <france.visconti@gmail.com>
     9  Jose Enrique Ruiz <jer@iaa.es>
     9  Markus Gaug <markusgaug@gmail.com>
     6  Paolo Cumani <pcumani@ifae.es>
     6  Thomas Gasparetto <thomas.gasparetto@ts.infn.it>
     5  Lukas Nickel <lukas.nickel@tu-dortmund.de>
     5  Ruben Lopez-Coto <rlopezcoto@gmail.com>
     4  Michele Peresano <peresano.michele@gmail.com>
     4  Tristan Carel <tristan.carel@lapp.in2p3.fr>
     3  Daniel Nieto <nieto@gae.ucm.es>
     3  Michael Punch <michael.punch@lnu.se>
     3  Miguel Nievas <miguelnievas@ucm.es>
     3  Orel Gueta <orel.gueta@desy.de>
     2  Cyril Alispach <cyril.alispach@unige.ch>
     2  Julien Lefaucheur <jjlk@users.noreply.github.com>
     2  Konstantin Pfrang <konstantin.pfrang@desy.de>
     2  Moritz Hütten <mhuetten@mpp.mpg.de>
     2  Thomas Armstrong <thomas.armstrong@physics.ox.ac.uk>
     1  Alice Donini <40267450+adonini@users.noreply.github.com>
     1  David Landriu <landriu@sappcm22.extra.cea.fr>
     1  Gernot Maier <gernot.maier@desy.de>
     1  Jonas Hackfeld <jonas.hackfeld@ruhr-uni-bochum.de>
     1  Lab Saha <lab.saha@gmail.com>
     1  Mireia Nievas-Rosillo <mireia.nievas-rosillo@desy.de>
     1  Noah Biederbeck <nbiederbeck@tutanota.com>
     1  Pierre Aubert <aubertp7@gmail.com>
     1  Sabrina Einecke <sabrina.einecke@tu-dortmund.de>
     1  Yves Renier <yves.renier@cern.ch>
     1  momorning <55380737+momorning@users.noreply.github.com>
```

@Hckjs  @yrenier are you fine with this inclusion?

@momorning Would you also like to be recognised in the logs with a proper name and email address?

### CODE REVIEW

**Comment by yrenier** [comment]
Sure, but could you please change the e-mail to yves.renier@unige.ch ?

**Comment by Hckjs** [comment]
@MaxNoe ofc, thanks!

**Comment by MaxNoe** [comment]
done

**Comment by watsonjj** [comment]
Can you update my email to jason.watson@desy.de please

**Comment by MaxNoe** [comment]
@watsonjj done

**Pull request merged**
