### PR TITLE
Append mode for HDF5Table

### PR DESCRIPTION
**Pull request by calispac**
This solves the first issue in #687.
I have updated the notebook to show the new feature.
I will find some time to write tests

I also added the possibility to write to an existing group_name. This will work only if the table name does not exist already. I am not sure if this feature is wanted.

### CODE REVIEW

**Comment by kosack** [comment]
I still don't think this is necessary, since you can already pass `mode='a'` and it should work.  There are also many other parameters you can pass, like `filters=tables.Filters(complevel=5, complib='blosc')` if you want compression.  Perhaps we just need to update the documentation to be more explicit?

**Comment by kosack** [comment]
see #690 - does this fix the problem?

**Comment by calispac** [comment]
I just updated this PR to what was discussed and what is in this PR #690 . I can make the notebook a bit better to show what types are supported and how one could proceed to save different Containers and SubContainers.

**Comment by kosack** [comment]
Also, all the tests seem to be failing (mainly because the first test, which writes out a file fails, so the others which read it also fail). Not sure why

**Comment by calispac** [comment]
I think test first test was failing because `mode` was not set to `mode='w'`. By default pytables.open_file() sets `mode='r'`. See http://www.pytables.org/usersguide/libref/top_level.html?highlight=tables%20open_file#tables.open_file

I see that one can pass `root_uep` to this so I will try to make it work such that one can specify the location of the group

**Comment by calispac** [comment]
I realized that in the reader `__init__()` one variable is called : 'table_name'. In fact this is not really a name but a location in the table.  Should we rename this variable?

**Comment by calispac** [comment]
Concerning the Root Entry Point. By default `pytables` does not allow to write to a non existing group. e.g. : 

If one does this in an empty file:

```python
tables.open_file('my_group', root_uep='/a_non_existing_group_path')
```
an an `HDF5ExtError` is issued. See : https://www.pytables.org/usersguide/libref/file_class.html?highlight=file#tables.File.create_group

So my question is should we allow do as `pytables` does or should we allow to write to any location whether or not the group exists ?. In any case I think we can address this to a future PR.

**Pull request merged**
