### PR TITLE
Support reading time objects, make sure to write out TAI

### PR DESCRIPTION
**Pull request by maxnoe**
Adds meta fields `{col_name}_TIME_SCALE / FORMAT`, by now always  `tai`  and `mjd` and parses back into time.

### CODE REVIEW

**Review by kosack — APPROVED** [review]
good idea

**Review by kosack — CHANGES_REQUESTED** [review]
could you also add a similar transform to `io.astropy_helpers.h5_table_to_astropy` ?

**Comment by maxnoe** [comment]
@kosack This changes our `NAN_TIME` marker to have be 0 MJD (TAI), which should clearly communicate an invalid date (it's in 1857) but does not have problems with astropy time and nan, which is an open issue with astropy.

**Comment by maxnoe** [comment]
@kosack done

**Review by kosack — APPROVED** [review]

**Comment by maxnoe** [comment]
Superseded by #1586

**Pull request closed without merging**
