### PR TITLE
Add MC xmax info

### PR DESCRIPTION
**Pull request by mackaiver**
Adds the xmax info to the MC container. This can be used as soon as the new pyhessio is used in ctapipe with this PR https://github.com/cta-observatory/pyhessio/pull/62

### CODE REVIEW

**Comment by kosack** [comment]
I'll build a package for the new pyhessio and upload it shortly, then this should work.

**Comment by kosack** [comment]
there is now a pyhessio-2.1.0 package in the cta-observatory channel (for linux, mac, and py35, py36). Try updating the environment.yml and setup.py to require >=2.1 and see if it works.  I haven't done any testing.

**Comment by mackaiver** [comment]
It works 👍

**Comment by kosack** [comment]
Great! Looks like it works. I'll merge it in.

**Pull request merged**
