### PR TITLE
Add pyproject toml

### PR DESCRIPTION
**Pull request by MaxNoe**
Reference for pyproject.toml and why we should have one:
https://www.python.org/dev/peps/pep-0518/
https://www.python.org/dev/peps/pep-0517/
https://snarky.ca/what-the-heck-is-pyproject-toml/

### CODE REVIEW

**Comment by kosack** [comment]
Should we put any other config in there while we're at it? Like `black` configs? (https://github.com/psf/black/blob/master/pyproject.toml) - the defaults are pretty much correct, but it might be nice to specify only the python version we support so it uses modern features when possible, and also to exclude files it shoudn't format when running in recursive mode.  Soon I would like to install it as a pre-commit hook, after we reformat all code, so we fix all small style problems. If the config is already there, that would help.

**Comment by kosack** [comment]
I guess this can eventually replace setup.py, but it seems like the features are not all there yet (installing in developer mode for example). I wonder if conda will support it eventually? Right now, I build the conda package in a pretty automated fashion, reading the necessary info from setup.py, but that will break I guess if we go full PEP 517

**Comment by MaxNoe** [comment]
There is no "full" pep 517. You need a build system. You can now specify that build system in the pyproject.toml.

But you still have to choose `setuptools`, or `poetry` or something else.
We could think about switching to poetry. But I think that's another matter.

**Comment by MaxNoe** [comment]
I added the black config

**Comment by kosack** [comment]
> There is no "full" pep 517. You need a build system. You can now specify that build system in the pyproject.toml.

What I meant was this quote here from the article above: 

> But there's a bonus if you use a pyproject.toml file with a setup.cfg configuration for setuptools: you don't need a setup.py file anymore! 

Right now we have a mix of setup.py, setup.cfg, and pyproject.toml.  But I guess that's fine for now.

**Comment by MaxNoe** [comment]
Ah ok. But we probably want to keep the automatic versioning, right? So that needs a script, not just a config.

**Comment by watsonjj** [comment]
Does this address #1159?

**Comment by MaxNoe** [comment]
@watsonjj now, it just adds a config, it does not run black by itself

**Pull request merged**
