### PR TITLE
Make ctapipe-extra truly optional

### PR DESCRIPTION
**Pull request by MaxNoe**
ctapipe-extra was not listed in setup.py as required but was actually required in several places.

This should make it a truly optional dependency

### CODE REVIEW

**Comment by kosack** [comment]
should it be optional? It defines a lot of required defaults. They can of course be overwritten by users using $CTAPIPE_SVC_PATH, but many things won't work without at least the defaults defined.  Of course, it will be refactored soon to be a bare minimum, but I think it's still required for normal operation.

**Comment by MaxNoe** [comment]
> It defines a lot of required defaults.

It does? Where are those used?

Currently, `ctapipe_resources` is not mentionend in `install_requires`.

**Comment by MaxNoe** [comment]
I tested several things now, e.g. doing hillas reconstructiion on mc.

Nothing needed ctapipe-extra.

I also grepped through the code for stuff like `get_dataset_path`, only the tests use it, or the tools for example data. 

I think we should go forward and merge this.

**Comment by kosack** [comment]
I guess it will break ctapipe-camdemo and most of the tutorials however, so  it's still "somewhat" required. I'd prefer to keep it at least in the conda package as a dependency, and we could always rename ctapipe-extra to ctapipe-resources (which is the only package inside it so far, so would make more sense), and then the semantic problem is gone.

**Comment by MaxNoe** [comment]
@kosack it already has.

**Comment by dneise** [comment]
@kosack  this is the current setup.py in the master:

https://github.com/cta-observatory/ctapipe/blob/cc215e2f7233973ff1b604f90c96ac8cea447fcd/setup.py#L76-L80

**Comment by MaxNoe** [comment]
Ok, I added a small fix for setup.py, please review again @kosack @dneise

**Pull request merged**
