### PR TITLE
Change telid to tel_id everywhere and run black on those files.

### LINKED ISSUE #1457: Change telid to tel_id everywhere.
```
❯ rg tel_id | wc -l
423
❯ rg telid | wc -l
256
```

### PR DESCRIPTION
**Pull request by nbiederbeck**
Fixes #1457.

### CODE REVIEW

**Comment by maxnoe** [comment]
As this might interfere with many open PRs, I would do this again as the last commit before making the next release.

Similar to #1345

**Review by kosack — APPROVED** [review]

**Comment by kosack** [comment]
You need to fix the conflicts (since the same files were touched by a recent PR), but should be easy.

**Comment by maxnoe** [comment]
As I've said, I would just run it again just before we want to create the next release.

**Comment by maxnoe** [comment]
Close and will redo as last commit before making 0.10

**Pull request closed without merging**
