### PR TITLE
remove optional deps in order to fix tests

### PR DESCRIPTION
**Pull request by dneise**
Currently the build of the master fails. This PR intends to fix this by removing optional dependencies which are not conda packages

### CODE REVIEW

**Comment by dneise** [comment]
We found that `numpy>=1.15.4` results in conda installing a py3.6 even if we installed a py3.5 previously in that environment. So we did not really test on py3.5 since some time ... we just thought we did.

So I also removed the py3.5 test

**Comment by MaxNoe** [comment]
Don't we need `codecov` for the `pytest --coverage` call?

**Comment by dneise** [comment]
I do not know that

**Comment by dneise** [comment]
Sorry @MaxNoe I did might have misunderstood the question. Did I modify something regarding codecov?

**Comment by MaxNoe** [comment]
> Did I modify something regarding codecov?

Yes, you removed `pip install codecov` from the travis yaml

**Comment by dneise** [comment]
ah yes now I see ... I removed one line too many

**Comment by dneise** [comment]
I think it is needed in the `after success` part .. so I will observe the current build to see if the tests pass now .. and only then re-add the line I removed accidentally.

**Comment by dneise** [comment]
I removed some tests for pyhessio earlier, but since we omitted OSX these tests might actually run again. Also CodeCov complained about these missing tests.

**Pull request merged**
