### PR TITLE
Fix SST-1M to be DC and not SC. Solves #905

### PR DESCRIPTION
**Pull request by thomasgas**

### CODE REVIEW

**Comment by MaxNoe** [comment]
But LST is not Davies Cotton afaik, its parabolic

**Comment by thomasgas** [comment]
> But LST is not Davies Cotton afaik, its parabolic

You're right. So i guess that by now "DC" is kind of an alias for "1-mirror-telescope" and "SC" is for "2-mirror-telescope". Which is clearly wrong...
what shall we do with this LUT? fill it with correct info or create it from the mc?

**Comment by kosack** [comment]
This info is there since one is not always reading an MC file, so you need a lookup for it. Also at the time, it wasn't possible to read it from the MCs - is there now some accessor? 

For the names, I agree it's not ideal - we can easily change the optics type names, however, since they are not fixed or used anywhere yet.  The main reason was to be able to adapt algorithms to different types, which could be simply the number of mirrors, but also may have other aspects such as off-axis corrections.  I'm happy if we update these to be correct, or use better names.    

* SC: Swartzschild-Couder
* DC: Davies Cotton
* might need another for modified Davies-Cotton (e.g. LST) - is there a name for that optics type?

**Comment by thomasgas** [comment]
so do you want to merge this or do you want to change LST optics.mirror_type in order to be consistent?

**Comment by MaxNoe** [comment]
Apply this simple fix now, i'd say, rest later

**Comment by GernotMaier** [comment]
For completeness: the 1-mirror MST has a 'modified DC design' (something between DC and parabolic).

I don't think this matters anywhere (unless one needs e.g. the smearing in time due to the optics or if one wants to fold the expected optical PSF into the image reconstruction), and knowing that it is a one or two-mirror instrument should be enough.

**Pull request merged**
