### PR TITLE
Fix camera names

### PR DESCRIPTION
**Pull request by kosack**
- unify camera names
- better loading and searching for known cameras (in case no simtel file is open)

### CODE REVIEW

**Comment by kosack** [comment]
so far camera names look like this:
allcams

**Comment by kosack** [comment]
see also issue #255

**Comment by watsonjj** [comment]
Do you plan to change "GATE" to "CHEC" now? I noticed you reverted "GCT" back to "GATE".

**Comment by kosack** [comment]
this fixes #404

**Comment by kosack** [comment]
> Do you plan to change "GATE" to "CHEC" now? I noticed you reverted "GCT" back to "GATE".

I think GATE is gone now (at least it should be - do you see somewhere where it was missed?), it's only CHEC.  Note that GCT is the name of the telescope, but GATE is the name of the camera (this is the `camera_id`), so I think that makes the most sense.  Imagine for example putting a "GATE" camera on an Astri telescope, for example, and then it wouldn't make sense to call it GCT.  When I finish implementing the `TelescopeOptics` classes (which are like `CameraGeometry` but for the telescope), those will be associated with a telescope name and version (so 'GCT' would make sense there).

**Comment by kosack** [comment]
Never mind, I see in the figure above that there is still a GATE! I'll track down where it's coming from... Perhaps some place I forgot to fix a name.

**Comment by kosack** [comment]
I seem to be just crazy and accidently forgot which one was the camera name :) I'll fix it in the master.

**Comment by kosack** [comment]
@watson is it correct that the camera is called CHEC? or has it be renamed GCTCam or something?

**Comment by watsonjj** [comment]
Yes the camera is called CHEC :)

**Pull request merged**
