### PR TITLE
Fix broken urls in README

### PR DESCRIPTION
**Pull request by aknierim**
This fixes broken urls in the README after the restructuring of the docs.

### CODE REVIEW

**Review by Tobychev — APPROVED** [review]

**Comment by maxnoe** [comment]
Rebasing with main will fix the docs build

**Review by LukasNickel — DISMISSED** [review]

**Comment by maxnoe** [comment]
Something went wrong in your rebasing

**Comment by aknierim** [comment]
> Something went wrong in your rebasing

Yeah, can't figure out what, though...

**Comment by maxnoe** [comment]
Did you update upstream before the rebase?

```
git fetch upstream
git rebase upstream/main
```
?

**Comment by aknierim** [comment]
Yup, which is why I'm confused

**Review by maxnoe — APPROVED** [review]

**Review by kosack — APPROVED** [review]

**Pull request merged**
