### PR TITLE
updated AUTHORS with latest mailmap

### PR DESCRIPTION
**Pull request by kosack**
ran "git authors" to generate a new version

The new author list now has the correct emails for everyone

### CODE REVIEW

**Comment by MaxNoe** [comment]
> git: 'authors' is not a git command. See 'git --help'.

What exactly did you do?

**Comment by kosack** [comment]
> What exactly did you do?

```sh
rm AUTHORS
git authors
```
That's basically it (without the `rm` it tries to merge the authorlist with the previous version)

```
NAME
       git-authors - Generate authors report

SYNOPSIS
       git-authors [-l, --list] [--no-email]

DESCRIPTION
       Populates the file matching authors|contributors -i with the authors of commits, accord-
       ing to the number of commits per author. Opens the file in $EDITOR when set.

       See the "MAPPING AUTHORS" section of git-shortlog(1) to coalesce together commits by the
       same person.

```

**Comment by kosack** [comment]
(it's part of the git-extras package in case you don't have it)

**Comment by MaxNoe** [comment]
> (it's part of the git-extras package in case you don't have it)
That was the missing information, thanks!

**Pull request merged**
