### PR TITLE
Coordinates notebook pr

### PR DESCRIPTION
**Pull request by MaxNoe**
I Updated the coordinates notebook from here #861 to the current master and moved it to tutorials.

### CODE REVIEW

**Comment by kosack** [comment]
where are `ground_frame.png` and  `ground_tilted_frame.png` referenced in the notebook? I think they were missing in the original PR as well. @thomasgas do you have those?

**Comment by MaxNoe** [comment]
These are attachments, they are inside the notebook file.

**Comment by kosack** [comment]
Ah, ok I guess github's renderer just doesn't show them.

**Comment by kosack** [comment]
need to add it to `tutorials/index.rst` under *toctree*

**Comment by MaxNoe** [comment]
Okay, things are passing now

**Comment by thomasgas** [comment]
Thanks for working on this. I guess the only thing remaining is to add a piece of code for the TiltedGroundFrame.

**Comment by MaxNoe** [comment]
Lets merge this.  We cannot add more examples later. But I think its important to have this in the docs @thomasgas

**Pull request merged**
