### PR TITLE
 Reduce numba signatures to improve import time

### PR DESCRIPTION
**Pull request by watsonjj**
Addresses #1102

```
In [1]: %time from ctapipe.image import extractor
CPU times: user 1.54 s, sys: 260 ms, total: 1.8 s
Wall time: 1.51 s
```

### CODE REVIEW

**Comment by MaxNoe** [comment]
This splits the function into to functions, right?

Are there no uses of this function with `ndim=3`? If so, for what do we need the `_3d` function?

**Comment by kosack** [comment]
> Are there no uses of this function with ndim=3? If so, for what do we need the _3d function?

I guess the question is: do we still want to be able to integrate each gain channel separately in some cases (e.g. for checking linearity)? I guess it would be nice to have that, but could be added back later upon need as well.

**Comment by watsonjj** [comment]
As stated in #1095, I wanted to put the 3d waveform functionality of the charge extractors through a deprecation cycle. Splitting `neighbor_average_waveform` into two functions achieves this more elegantly. And neither of the two `neighbor_average_waveform` functions are compiled on import - only on call.

**Comment by watsonjj** [comment]
Also, `ctapipe.calib.camera.flatfield` and `ctapipe.calib.camera.pedestal` appear to import the extractors directly, and seem to somewhat do the calibration chain itself inside the classes, and therefore the tests still use the 3d waveform functionality of the extractors. I haven't had time to look into the code in detail, but I intend to investigate and refactor soon.

**Pull request merged**
