### PR TITLE
Fix examples, fixes #1331

### LINKED ISSUE #1331: Failing test and docs after clean installation of latest development version
I cleaned up my environment and re-installed the very latest version of the master branch (few minutes ago).

Installation goes ok, but one test fails and I am not sure if it's a real problem of something related to my setup.

```
______________________________________ ERROR collecting ctapipe/coordinates/tests/test_coordinates.py _______________________________________
ctapipe/coordinates/tests/test_coordinates.py:7: in <module>
    location = EarthLocation.of_site('Roque de los Muchachos')
../../anaconda3/envs/cta-dev/lib/python3.7/site-packages/astropy/coordinates/earth.py:351: in of_site
    registry = cls._get_site_registry()
../../anaconda3/envs/cta-dev/lib/python3.7/site-packages/astropy/coordinates/earth.py:532: in _get_site_registry
    reg = get_downloaded_sites()
../../anaconda3/envs/cta-dev/lib/python3.7/site-packages/astropy/coordinates/sites.py:139: in get_downloaded_sites
    jsondb = json.loads(content)
../../anaconda3/envs/cta-dev/lib/python3.7/json/__init__.py:348: in loads
    return _default_decoder.decode(s)
../../anaconda3/envs/cta-dev/lib/python3.7/json/decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
../../anaconda3/envs/cta-dev/lib/python3.7/json/decoder.py:355: in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
E   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
========================================================== short test summary info ==========================================================
ERROR ctapipe/coordinates/tests/test_coordinates.py - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

During the compiling process of the documentation:

I first get a warning from `astropy`, not sure if it's related,
`WARNING: IERSStaleWarning: leap-second file is expired. [astropy.utils.iers.iers]`

then the build fails with a lot of errors related to I/O and various containers,

at the very end I get an error which seems related to the one thrown by `pytest`, triggered in the notebook `tutorials/coordinates_example.ipynb`.

I attach the log output of the documentation compilation process for more details.

[make_doc_log_150520.zip](https://github.com/cta-observatory/ctapipe/files/4633927/make_doc_log_150520.zip)

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by HealthyPear** [comment]
All work well!

I would propose that in the pedestal calibration example we mode the plotting command inside the for cycle.
There are many other examples that work in the same way and it it sufficient to ctrl-c to exit.
At least the user sees something :)

**Comment by kosack** [comment]
It think you can remove `calc_pedestals.py` - it doesn't use the real pedestal calculation I think (and calib/pedestals.py doesn't even exist anymore)

**Comment by HealthyPear** [comment]
> It think you can remove `calc_pedestals.py` - it doesn't use the real pedestal calculation I think (and calib/pedestals.py doesn't even exist anymore)

 it uses `ctapipe.calib.camera.pedestals`

**Comment by MaxNoe** [comment]
For the test data there is this issue: https://github.com/cta-observatory/ctapipe/issues/558

**Comment by HealthyPear** [comment]
> For the test data there is this issue: #558

yes using (even the same) 2/3 events for every test that uses data is a good alternative that won't need to implement any additional interactive code in the examples

**Comment by kosack** [comment]
> yes using (even the same) 2/3 events for every test that uses data is a good alternative that won't need to implement any additional interactive code in the examples

it's already mostly like that.  I think we can ignore this for this release.

**Comment by HealthyPear** [comment]
Sure! this PR was not really urgent, it was just triggered by a clean installation I tried to play with the DL1 writer...

We can leave this for later if you want.

What to we want to do with the pedestal example?

**Comment by kosack** [comment]
> What to we want to do with the pedestal example?

It's ok now that it uses the correct method at least. We can improve it later

**Comment by MaxNoe** [comment]
@HealthyPear Could you make clear what changes you requested? Given that the example about pedestals states pretty clearly how to get the plots for all events, I would leave it like it is.

**Comment by HealthyPear** [comment]
> @HealthyPear Could you make clear what changes you requested? Given that the example about pedestals states pretty clearly how to get the plots for all events, I would leave it like it is.

It was just to make it more direct and useful for an eventual user: right now the last event (which is what the script plots) gives an empty plot.
I was suggesting to place the plotting command inside the events cycle (which is the case anyway for many other examples), so at least we show something without the need for the user to modify the script.

**Comment by MaxNoe** [comment]
@HealthyPear I added a check for `num_samples > 1` so that the plot shows an image and no nans are reported on the command line.

@kosack please review again

**Pull request merged**
