### PR TITLE
Move container definition into image module

### PR DESCRIPTION
**Pull request by MaxNoe**
This solves the circular import Problem @HealthyPear is facing in #1215 .

As image imported these containers from io, it imported the whole simetelevent source which imports the calibration stack which imports something from image.

### CODE REVIEW

**Comment by kosack** [comment]
with this cause (or solve) any circular imports?

**Comment by MaxNoe** [comment]
@kosack solves, see new description.

**Comment by kosack** [comment]
Ok, though now `reco` will depend on `image`, but that may have already been the case.

**Comment by MaxNoe** [comment]
This is the chain:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/image/__init__.py", line 1, in <module>
    from .hillas import *
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/image/hillas.py", line 11, in <module>
    from ..io.containers import HillasParametersContainer
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/__init__.py", line 8, in <module>
    from .simteleventsource import SimTelEventSource
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 18, in <module>
    from ctapipe.calib.camera.gainselection import ThresholdGainSelector
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/calib/__init__.py", line 5, in <module>
    from .camera import *
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/calib/camera/__init__.py", line 6, in <module>
    from .calibrator import CameraCalibrator
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/calib/camera/calibrator.py", line 9, in <module>
    from ctapipe.image.extractor import NeighborPeakWindowSum
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/image/extractor.py", line 30, in <module>
    from ctapipe.image.timing_parameters import timing_parameters
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/image/timing_parameters.py", line 8, in <module>
    from .hillas import camera_to_shower_coordinates
```

**Comment by MaxNoe** [comment]
@kosack I like the fact that they are defined where they are used / emitted

**Comment by MaxNoe** [comment]
Ah dam, I introduced another circular import.

**Comment by kosack** [comment]
> I like the fact that they are defined where they are used / emitted

I do to, but often  you don't need the algorithm to use the data, so if they are grouped, you entangle them

**Comment by kosack** [comment]
You can check with something like:
```bash
pydeps --show-cycles --max-bacon=2 --cluster --keep-target-cluster -T png ctapipe
```

**Comment by MaxNoe** [comment]
ctapipe

**Comment by MaxNoe** [comment]
@kosack that does not really seem to work, as I back import the containers in io but it does not show a dependency from io to image

**Comment by kosack** [comment]
> Or does it only show cycles?

I think with those options, it only shows cycles. If you show everything it's huge.

**Comment by HealthyPear** [comment]
The errors in the log now seem to be different, they don't show anymore a circular import: there seems to be a problem with notebooks and the stub file from `HillasParametersContainer`

**Comment by MaxNoe** [comment]
Ok, so I now moved all image related containers into the image submodule and removed them from io.

The only reason to remove them from io is that the docs create a warning, which is treated as error on travis. This is not good I think.

Also, does this create problems with the table reader? If the containers are not all in io/containers anymore?

Maybe better to just move the container definions into their own submodule? `ctapipe.containers`?

**Comment by HealthyPear** [comment]
> Maybe better to just move the container definions into their own submodule? `ctapipe.containers`?

I would do this, it seems a cleaner approach

**Pull request closed without merging**
