### PR TITLE
Changes to NectarCAMEventSource

### PR DESCRIPTION
**Pull request by watsonjj**

### CODE REVIEW

**Comment by watsonjj** [comment]
Something odd seems to be happening when reading a NectarCAM file for a second time (see the error message that occurs in even the first commit, before any changes to the NectarCAMEventSource class). @dneise  Any idea why this error occurs (it happens inside protozfits/simple.py)

**Comment by dneise** [comment]
I believe this is connected to an issue I ran into nearly a month ago .. but I was too lazy to even completely describe the issue. I am very sorry. 

https://github.com/cta-sst-1m/protozfitsreader/issues/25

**Comment by kosack** [comment]
Can you merge in the master now and fix the conflicts? I merged #734, so perhaps that will resolve this

**Comment by watsonjj** [comment]
A segfault is thrown when one of these events go through `ctapipe.utils.neighbour_sum.get_sum_array`, likely due to the dual channels. Its probably not worth fixing as there will be only one channel at that level when #683 is merged.

**Pull request closed without merging**
