### PR TITLE
Fix enum deserialization in HDF table writer

### PR DESCRIPTION
**Pull request by maxnoe**
Worked before only if there is only one field in the container due to a reference issue

### CODE REVIEW

**Comment by maxnoe** [comment]
The test in commit 1 fails on master and commit 2 contains the fix.

**Comment by LukasNickel** [comment]
For context: This fixes #1482. For now we still rely on pickle until we decide whether we want to change that.

**Review by LukasNickel — APPROVED** [review]

**Comment by maxnoe** [comment]
The issue is linked, @LukasNickel ;)

**Comment by LukasNickel** [comment]
> The issue is linked, @LukasNickel ;)

I'm blind, mea culpa :)

**Review by kosack — APPROVED** [review]

**Pull request merged**
