### PR TITLE
Make sure unit is really a unit, use fits format

### PR DESCRIPTION
**Pull request by MaxNoe**
Fix for the strange unit in the metadata as seen in @kosack  talk:

Screenshot_20200519_172143

### CODE REVIEW

**Comment by kosack** [comment]
yeah, I noticed that during the talk! clearly a but strange

**Comment by kosack** [comment]
perhaps "vounit" format should be used. It's similar to FITS, but a but more modernized

**Comment by MaxNoe** [comment]
Changed to vounit format

**Comment by MaxNoe** [comment]
Ubuntu 18.04, Codename bionic beaver

**Pull request merged**
