### PR TITLE
Implement a path trait

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by MaxNoe** [comment]
@kosack The tests fail because of some unrelated sphinx error, can you check?

**Comment by kosack** [comment]
>The tests fail because of some unrelated sphinx error, can you check?

seems that automodsumm either was updated, or needs to be updated to sync with sphinx. I'll try fixing the version number to an older one.

**Comment by kosack** [comment]
This is nice. You may need to add a check that it is not a URL in the validator though, since so far things like `HESSIOEventSource` accept either URL for a remote file or a file path for local ones. If we change to a `Path` trait, then it would break that behavior.

**Comment by kosack** [comment]
The sphinx problem should be fixed now.

**Comment by MaxNoe** [comment]
> This is nice. You may need to add a check that it is not a URL in the validator though, since so far things like HESSIOEventSource accept either URL for a remote file or a file path for local ones. If we change to a Path trait, then it would break that behavior

Ah, I didn't know that. So having an URL trait might make sense as well

**Comment by MaxNoe** [comment]
But adding this trait doesn't mean we have to use it everywhere, I was thinking about using it the example I talked about here #658

**Comment by kosack** [comment]
> But adding this trait doesn't mean we have to use it everywhere
agreed - it's still quite useful.

**Comment by dneise** [comment]
Could you describe what this is about?

**Comment by dneise** [comment]
Do I understand correctly? 
 * `exists=False` means "The file/dir must not exist." .. 
 * `exists=True` means "The file/dir must exist." ..

How does: "I don't care if they exist" work? `exists=None`?

**Comment by MaxNoe** [comment]
> How does: "I don't care if they exist" work? exists=None?
Yes, this is the default

**Comment by dneise** [comment]
There are a couple of Python built in exceptions like [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) or [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError)  

I was wondering if these are probably better suited to raise here, than a pretty generic `TraitsError`. ... but then again .. maybe TraitsError is just the right thing here.

**Comment by dneise** [comment]
> How does: "I don't care if they exist" work? exists=None? - Yes, this is the default

Great thanks.

**Comment by MaxNoe** [comment]
Oh yes, you are right. Haven't thought about it, just followed the example in the traitlets docs.

**Pull request merged**
