### PR TITLE
Update stage1 example config with new cleaning levels

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by bregeon** [comment]
may I ask what happens to the FlashCam cleaning with that config file?
it's default 10/10?

**Comment by maxnoe** [comment]
Good catch, should have been 10/5

**Comment by bregeon** [comment]
ok, that matches what we discussed on Slack.
May I just ask also why having a default instead of defining explicitly numbers for FlashCam as well?

**Comment by bregeon** [comment]
also did we discuss the ImageQualityQuery parameters, are they ok?

**Review by kosack — DISMISSED** [review]

**Comment by kosack** [comment]
> also did we discuss the ImageQualityQuery parameters, are they ok?

Those are pretty reasonable.  Below 50 PE, you get lots of crazy systematics, so as a default/example it's fine. The user can of course choose what they like

**Comment by maxnoe** [comment]
> also did we discuss the ImageQualityQuery parameters, are they ok?

Also, these are only relevant for the parameters, all images are stored.

**Review by bregeon — DISMISSED** [review]
Looks good to me now.

**Review by bregeon — APPROVED** [review]
still good for me

**Comment by maxnoe** [comment]
> also did we discuss the ImageQualityQuery parameters, are they ok?

Also, these are only relevant for the parameters, all images are stored.

**Comment by maxnoe** [comment]
@kosack approve again? Then we have this in 0.10.3

**Review by HealthyPear — APPROVED** [review]
what about the other SSTs? I thought there were 3 of them in total, but perhaps something changed recently and I didn't follow

**Comment by maxnoe** [comment]
@HealthyPear Prod5 has only one SST.

**Pull request merged**
