### PR TITLE
Update Timing Parameters

### PR DESCRIPTION
**Pull request by LukasNickel**
* use container for output
* use geometry, peakpos and hillas_parameters as input
* adapt test

### CODE REVIEW

**Comment by MaxNoe** [comment]
We just rebased our stuff onto master, why was the merge needed?

**Comment by MaxNoe** [comment]
@LukasNickel is a new master student in Dortmund, btw.

**Comment by MaxNoe** [comment]
I'm cannot explain why coverage of `tools/camdemo.py` went down. How is this possible?

**Comment by MaxNoe** [comment]
@LukasNickel can you fix the stuff that codacy complains about?

**Comment by LukasNickel** [comment]
> @LukasNickel can you fix the stuff that codacy complains about?

Going to do that asap.
Do we just not worry about the camdemo coverage? I can't see any changes in the file at all.

**Comment by MaxNoe** [comment]
> Do we just not worry about the camdemo coverage? I can't see any changes in the file at all.

Yes, not related to this PR.

**Comment by kosack** [comment]
> Do we just not worry about the camdemo coverage? I can't see any changes in the file at all.

that seems to be a false positive, so just ignore it. Not sure why it came up in this PR.

**Pull request merged**
