### PR TITLE
Add docstring for ctapipe-train-disp-reconstructor

### LINKED ISSUE #2283: ctapipe-train-disp-reconstructor missing docstring
```
% ctapipe-info --tools

...
ctapipe-train-disp-reconstructor  - [no documentation. Please add a docstring]
...
```

### PR DESCRIPTION
**Pull request by LukasBeiske**
Fixes #2283

### CODE REVIEW

**Review by Tobychev — DISMISSED** [review]

**Comment by ccossou** [comment]
I'm trying to review this, @LukasBeiske are you available now? I have a few questions.

**Comment by maxnoe** [comment]
It's also missing from the sphinx documentation, could you add it please?

**Comment by maxnoe** [comment]
https://github.com/cta-observatory/ctapipe/blob/main/docs/api-reference/tools/index.rst

**Comment by ccossou** [comment]
As far as I understand, this solves the issue, but I don't understand why the corresponding docstring has to be at the top of the file, instead of just using the one that already exist in the tool class **TrainDispReconstructor**.

**Comment by maxnoe** [comment]
@ccossou I agree, the ctapipe-info tool should use the class docstring, not the module docstring

**Comment by ccossou** [comment]
Am I supposed to approve it now, even though we still need to change the documentation (cf comment by max)? 

I assume our comments about using the class docstring are more for a future pull request about a refactoring of ctapipe-info and shouldn't block this one, but that's my opinion only.

**Comment by maxnoe** [comment]
> I assume our comments about using the class docstring are more for a future pull request about a refactoring of ctapipe-info and shouldn't block this one, but that's my opinion only.

Yes, let's do this separately.

**Comment by maxnoe** [comment]
You need to replace some single ticks with double ticks in the docstrings:

https://github.com/cta-observatory/ctapipe/actions/runs/6669605856/job/18127742839?pr=2420#step:6:124

**Comment by LukasBeiske** [comment]
> You need to replace some single ticks with double ticks in the docstrings:
> 
> https://github.com/cta-observatory/ctapipe/actions/runs/6669605856/job/18127742839?pr=2420#step:6:124

I'm not finding any and the docs build fine for me locally.

**Comment by LukasBeiske** [comment]
I noticed that the default target column of the `DispReconstructor` is still called `true_norm`. This target column never gets written out anywhere, since it gets calculated just before training the models, so its name does not really matter, but by now the target column that gets calculated is actually `true_norm * true_sign`. 
To avoid unnecessary confusion, I would suggest just naming this target column `true_disp`. If you agree, should I just add that change here, since it changes only a single line of code?

**Review by ccossou — APPROVED** [review]

**Review by maxnoe — APPROVED** [review]

**Pull request merged**
