### PR TITLE
Implement first methods for muon reconstruction and analysis

### PR DESCRIPTION
**Pull request by MaxNoe**
@pcumani and I were working on the muon reconstruction this week and implemented some first methods.

### Implemented stuff
* Reconstruction of ring parameters via gaussian likelihood fit with kundu chaudhuri formula as initial guess
* Estimation of the psf via a gaussian likelihood fit
* Estimation of the impact parameter via a binned χ²-Fit
* Estimation of optical efficiency using all of the above and the theoretical light distribution as described in @AMWMitchell s ICRC proceeding

* Some features for event selection

### Some open questions we have:
* How are units to be handled?
* Do you have ideas for more tests?

### Some first results:
We applied the methods to LST Mono muon monte carlo data.  
The scripts we used are in http://github.com/maxnoe/cta-muons  

* Fits of two well reconstructed muons:
nice_muon-035

nice_muon-049

* Distribution of the radius for selected muon events:
muon_cherenkov_angle

* PSF (standard deviation of gaussian fit)
muon_psf

* Impact Parameter vs. Ring Completeness:
impact_vs_completeness

* Optical Efficiency
optical_efficiency

### CODE REVIEW

**Comment by kosack** [comment]
Very nice.  I won't yet merge this in yet however, since there are at least 2 other implementations of muon fitting underway and it would be nice to make sure everyone uses the same structure so that we can compare results.   @rdelosreyes  will coordinate that at the F2F meeting.

**Comment by ParsonsRD** [comment]
Hi, I was about to submit a pull request for the same piece of code this week :-), although yours is likely a little better tested than mine. Will you be at the meeting next week? Maybe we could talk about about the method and we may be able to merge in some of my code if it is helpful.

**Comment by kosack** [comment]
This will definitely be a break-out session at the workshop, so we can make sure all efforts are merged then! It's ok to have two implementations, but they should use the same API and have the same inputs/outputs.

**Comment by rdelosreyes** [comment]
It is great to have already all this work done. It will definitively be a really valuable input.

Karl is right, DATA together with CCF  have organized a break-out session for the implementation of the muon reconstruction during the incoming Pipelines F2F meeting in Paris. There, we will examine what has been already produced and what will be finally delivered to ctapipe. The algorithms to be implemented have been studied within the CCF group and I think the best is that its implementation is validated together with them.

**Comment by AMWMitchell** [comment]
From a brief email exchange with Max, Paolo Cumani plans to present this implementation at the meeting next week. At the meeting, much as Raquel says, we can test the work done so far, identify tasks, and work together on an implementation for ctapipe.

**Comment by pcumani** [comment]
Hi, Just to confirm what @AMWMitchell said: unfortunately @MaxNoe will not be in Paris for the discussion, but I will and I can present it.

**Comment by rdelosreyes** [comment]
Hi Max,

During the Pipelines meeting in Paris it was set up and defined the basic structure of the muon calibration tasks as well as a ctapipe branch (muonmaster) to collect all the contributions. 
Looking at your code I think your input will help very much to improve the current scheme of the muon calibration.
I ask you then for your contribution to the muonmaster branch.
I will add few comments to the different parts of your code that I think it will be very useful to include in the current muonmaster branch.

Thank you very much in advance for your help.

**Comment by MaxNoe** [comment]
I will close this pull request now, update my code to the use the new classes and reopen it against the muonmaster.
However, I think the muonmaster should live as short as possible. We should merge to master as often as possible and as soon as we have a new function / component.

**Pull request closed without merging**
