### PR TITLE
Treat sphinx warnings as erros, fix deploy workflow name

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by maxnoe** [comment]
We have a whopping 839 warnings.  Most of them I think are because we use a single tick instead of a double tick for pre-formatted text in most places. For rst, single ticks are references, so we get tons of Unknown reference warnings.

**Review by kosack — APPROVED** [review]

**Comment by maxnoe** [comment]
@kosack a bit premature, but I am working on it... 

Down to 729.

**Comment by maxnoe** [comment]
Most of the errors are coming from the `-n` option to check for working links and the missing `traitlets` in the intersphinx docs.

**Comment by maxnoe** [comment]
Down to 76, yay.

**Review by kosack — APPROVED** [review]

**Comment by maxnoe** [comment]
Ok, massive commit, but it should build without warnings now. 

There should be no breaking changes for people importing the reconstructors / cutflow from the toplevel like this:

```
from ctapipe.reco import ImPACT
```

but some files (`ImPact`, `HillasReconstructor`, `CutFlow`) had to be renamed to disambiguate module from class references.

**Review by kosack — APPROVED** [review]
thanks! Looks like really tedious work, but much needed!

**Comment by maxnoe** [comment]
@kosack Unfortunately im kinda stuck.

I don't get the last two warnings in the CI locally. Seems to be something with the notebook

**Comment by maxnoe** [comment]
Ha, now it builds! Don't know what the problem was.

**Review by kosack — APPROVED** [review]

**Review by kosack — APPROVED** [review]

**Review by HealthyPear — APPROVED** [review]

**Pull request merged**
