### PR TITLE
Implement nan-handling like matplotlib high-level api

### PR DESCRIPTION
**Pull request by MaxNoe**
See https://github.com/matplotlib/matplotlib/issues/9892

### CODE REVIEW

**Comment by MaxNoe** [comment]
Needs #1051 for travis to pass

**Comment by MaxNoe** [comment]
I rebased against master, please review again

**Comment by thomasarmstrong** [comment]
Checked the changes and it behaves as expected:

Screenshot 2019-04-24 at 09 34 22

**Comment by MaxNoe** [comment]
Hey @thomasarmstrong, I see that if you review code, you try to run it locally.

While that's a great idea to check if the code works, I think this not what these code reviews are intended to check. Tests should make sure that the code works. (That's a bit hard to do right for plotting code).

The reviews by humans are more intended to find stylistic issues and missing documentation / tests, unclear or misleading variable names etc.

**Comment by thomasarmstrong** [comment]
@MaxNoe, thats fair, but as you said tests can be a bit harder for plotting code, especially when it comes to stylistic choices! I do sometimes test out bits of code but mainly for my own curiosity and/or understanding, but I understand the point.

**Pull request merged**
