### PR TITLE
Add a note to CameraGeometry docs about from_name()

### LINKED ISSUE #2484: Inconsistent LSTCam pixels ordering when importing using CameraGeometry.from_name
The LSTCam pixel positions ordering obtained using `CameraGeometry.from_name('LSTCam')` differs from the ordering obtained using `subarray.tel[1].camera.geometry.pix_x `

Consequently, using `CameraGeometry.from_name('LSTCam')` leads to incorrect LST images as the pixels are arranged differently in the camera plane.

**To Reproduce**
0. `ctapipe.__version__ ` : 0.19.3
1. Compare `CameraGeometry.from_name('LSTCam').pix_x` and `tel.camera.geometry.pix_x`
(output of latter can also be seen in this tutorial -https://ctapipe.readthedocs.io/en/latest/auto_examples/core/InstrumentDescription.html#explore-some-of-the-details-of-the-telescopes)

 

**Expected behavior**
The ordering should be same in both cases (it is same for other telescopes (FlashCam, NectarCam, CHEC)).

**Supporting information**
Simple plots of pix_x and pix_y positions from both methods.

image
image

**Additional context**

### PR DESCRIPTION
**Pull request by kosack**
Note that from_name() is not guaranteed to correspond with event data.

Closes #2484

### CODE REVIEW

**Comment by maxnoe** [comment]
CameraTypes is a set, you can't Index it

**Comment by maxnoe** [comment]
Can we  (also?) raise an actual code warning?

i.e.:

```
warnings.warn(".from_name methods use pre-defined data that is likely different from the data being analyzed. Access instrument information via the SubarrayDescription instead.")
```

**Review by Tobychev — DISMISSED** [review]

**Review by Tobychev — DISMISSED** [review]

**Comment by maxnoe** [comment]
The docs failure here is real and due to the changes made

**Review by maxnoe — APPROVED** [review]

**Comment by maxnoe** [comment]
@kosack, I added the actual warning now to those methods and made it fail the CI if it occurs unexpectedly.

It's your PR, so you cannot really approve, but please have a look.

@Tobychev  please review again :)

**Review by Tobychev — APPROVED** [review]

**Pull request merged**
